// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spring/interaction.proto

package com.hcsy.spring.proto.interaction.v1;

public final class InteractionOuterClass {
  private InteractionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030spring/interaction.proto\022\tspring.v1\032\023c" +
      "ommon/result.proto2\351\003\n\013Interaction\022:\n\rCo" +
      "mmentScores\022\026.common.v1.JsonRequest\032\021.co" +
      "mmon.v1.Result\0227\n\nLikeCounts\022\026.common.v1" +
      ".JsonRequest\032\021.common.v1.Result\022:\n\rColle" +
      "ctCounts\022\026.common.v1.JsonRequest\032\021.commo" +
      "n.v1.Result\0229\n\014FollowCounts\022\026.common.v1." +
      "JsonRequest\032\021.common.v1.Result\0226\n\tUserLi" +
      "kes\022\026.common.v1.JsonRequest\032\021.common.v1." +
      "Result\0229\n\014UserCollects\022\026.common.v1.JsonR" +
      "equest\032\021.common.v1.Result\022>\n\021UserFollowe" +
      "rCount\022\026.common.v1.JsonRequest\032\021.common." +
      "v1.Result\022;\n\016CommentsCreate\022\026.common.v1." +
      "JsonRequest\032\021.common.v1.ResultB<\n$com.hc" +
      "sy.spring.proto.interaction.v1P\001Z\022app/pr" +
      "oto/springv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
