version: "3.8"

services:
  gateway:
    image: mix-gateway:latest
    container_name: mix-gateway
    env_file:
      - ./gateway/.env.docker
    ports:
      - "8080:8080"
    environment:
      NACOS_SERVER: nacos:8848
      REDIS_HOST: redis
      GOZERO_HOST: gozero
    networks:
      - hcsy

  spring:
    image: mix-spring:latest
    container_name: mix-spring
    env_file:
      - ./spring/.env.docker
    ports:
      - "8081:8081"
    environment:
      NACOS_SERVER: nacos:8848
      DB_HOST: mysql
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ./spring/application.yaml:/app/application.yaml:ro
      - ./logs/spring:/app/logs/spring
      - ./static/pic:/app/static/pic
      - ./static/excel:/app/static/excel
      - ./static/upload:/app/static/upload
    networks:
      - hcsy

  gozero:
    image: mix-gozero:latest
    container_name: mix-gozero
    env_file:
      - ./gozero/app/.env.docker
    ports:
      - "8082:8082"
    environment:
      SERVER_IP: 0.0.0.0
      NACOS_IP: nacos
      DB_MYSQL_HOST: mysql
      DB_ES_HOST: es
      DB_MONGODB_HOST: mongodb
      RABBITMQ_HOST: rabbitmq
      LOGS_PATH: /app/logs/gozero
    volumes:
      - ./gozero/app/etc:/app/etc:ro
      - ./logs/gozero:/app/logs/gozero
      - ./static/pic:/app/static/pic
      - ./static/excel:/app/static/excel
      - ./static/upload:/app/static/upload
    networks:
      - hcsy

  nestjs:
    image: mix-nestjs:latest
    container_name: mix-nestjs
    env_file:
      - ./nestjs/.env.docker
    ports:
      - "8083:8083"
    environment:
      SERVER_IP: 0.0.0.0
      NACOS_SERVER: nacos
      NACOS_PORT: 8848
      DB_HOST: mysql
      DB_MONGODB_HOST: mongodb
      RABBITMQ_HOST: rabbitmq
      LOGS_PATH: /app/logs/nestjs
    volumes:
      - ./nestjs/application.yaml:/app/application.yaml:ro
      - ./logs/nestjs:/app/logs/nestjs
      - ./static/pic:/app/static/pic
      - ./static/excel:/app/static/excel
      - ./static/upload:/app/static/upload
    networks:
      - hcsy

  fastapi:
    image: mix-fastapi:latest
    container_name: mix-fastapi
    env_file:
      - ./fastapi/.env.docker
    ports:
      - "8084:8084"
    environment:
      SERVER_IP: 0.0.0.0
      NACOS_SERVER: nacos:8848
      RABBITMQ_HOST: rabbitmq
      DB_MYSQL_HOST: mysql
      DB_POSTGRES_HOST: pgvector-db
      DB_MONGODB_HOST: mongodb
      DB_REDIS_HOST: redis
      DB_CLICKHOUSE_HOST: clickhouse
      LOGS_PATH: /app/logs/fastapi
    volumes:
      - ./fastapi/application.yaml:/app/application.yaml:ro
      - ./logs/fastapi:/app/logs/fastapi
      - ./static/pic:/app/static/pic
      - ./static/excel:/app/static/excel
      - ./static/upload:/app/static/upload
    networks:
      - hcsy

networks:
  hcsy:
    external: true
