FROM apache/apisix:3.11.0-debian

COPY apisix/config.yaml /usr/local/apisix/conf/config.yaml
COPY apisix/apisix.yaml /usr/local/apisix/conf/apisix.yaml
COPY swagger-ui/ /usr/local/apisix/html/swagger-ui/
