// Server: spring
// Consumers: gozero,fastapi,nestjs

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: spring/article.proto

package springv1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_spring_article_proto protoreflect.FileDescriptor

const file_spring_article_proto_rawDesc = "" +
	"\n" +
	"\x14spring/article.proto\x12\tspring.v1\x1a\x13common/result.proto2\xcc\x02\n" +
	"\aArticle\x121\n" +
	"\x04List\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x122\n" +
	"\x05Batch\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x120\n" +
	"\x03Get\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x124\n" +
	"\aByTitle\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x127\n" +
	"\n" +
	"ViewsBatch\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x129\n" +
	"\fUserArticles\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB8\n" +
	" com.hcsy.spring.proto.article.v1P\x01Z\x12app/proto/springv1b\x06proto3"

var file_spring_article_proto_goTypes = []any{
	(*commonv1.JsonRequest)(nil), // 0: common.v1.JsonRequest
	(*commonv1.Result)(nil),      // 1: common.v1.Result
}
var file_spring_article_proto_depIdxs = []int32{
	0, // 0: spring.v1.Article.List:input_type -> common.v1.JsonRequest
	0, // 1: spring.v1.Article.Batch:input_type -> common.v1.JsonRequest
	0, // 2: spring.v1.Article.Get:input_type -> common.v1.JsonRequest
	0, // 3: spring.v1.Article.ByTitle:input_type -> common.v1.JsonRequest
	0, // 4: spring.v1.Article.ViewsBatch:input_type -> common.v1.JsonRequest
	0, // 5: spring.v1.Article.UserArticles:input_type -> common.v1.JsonRequest
	1, // 6: spring.v1.Article.List:output_type -> common.v1.Result
	1, // 7: spring.v1.Article.Batch:output_type -> common.v1.Result
	1, // 8: spring.v1.Article.Get:output_type -> common.v1.Result
	1, // 9: spring.v1.Article.ByTitle:output_type -> common.v1.Result
	1, // 10: spring.v1.Article.ViewsBatch:output_type -> common.v1.Result
	1, // 11: spring.v1.Article.UserArticles:output_type -> common.v1.Result
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spring_article_proto_init() }
func file_spring_article_proto_init() {
	if File_spring_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spring_article_proto_rawDesc), len(file_spring_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spring_article_proto_goTypes,
		DependencyIndexes: file_spring_article_proto_depIdxs,
	}.Build()
	File_spring_article_proto = out.File
	file_spring_article_proto_goTypes = nil
	file_spring_article_proto_depIdxs = nil
}
