// Server: spring
// Consumers: gozero,fastapi,nestjs

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: spring/article.proto

package springv1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Article_List_FullMethodName         = "/spring.v1.Article/List"
	Article_Batch_FullMethodName        = "/spring.v1.Article/Batch"
	Article_Get_FullMethodName          = "/spring.v1.Article/Get"
	Article_ByTitle_FullMethodName      = "/spring.v1.Article/ByTitle"
	Article_ViewsBatch_FullMethodName   = "/spring.v1.Article/ViewsBatch"
	Article_UserArticles_FullMethodName = "/spring.v1.Article/UserArticles"
)

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleClient interface {
	List(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	Batch(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	Get(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	ByTitle(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	ViewsBatch(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	UserArticles(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type articleClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleClient(cc grpc.ClientConnInterface) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) List(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Article_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) Batch(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Article_Batch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) Get(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Article_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) ByTitle(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Article_ByTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) ViewsBatch(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Article_ViewsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) UserArticles(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Article_UserArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
// All implementations must embed UnimplementedArticleServer
// for forward compatibility.
type ArticleServer interface {
	List(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	Batch(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	Get(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	ByTitle(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	ViewsBatch(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	UserArticles(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedArticleServer()
}

// UnimplementedArticleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServer struct{}

func (UnimplementedArticleServer) List(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedArticleServer) Batch(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Batch not implemented")
}
func (UnimplementedArticleServer) Get(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedArticleServer) ByTitle(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ByTitle not implemented")
}
func (UnimplementedArticleServer) ViewsBatch(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewsBatch not implemented")
}
func (UnimplementedArticleServer) UserArticles(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserArticles not implemented")
}
func (UnimplementedArticleServer) mustEmbedUnimplementedArticleServer() {}
func (UnimplementedArticleServer) testEmbeddedByValue()                 {}

// UnsafeArticleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServer will
// result in compilation errors.
type UnsafeArticleServer interface {
	mustEmbedUnimplementedArticleServer()
}

func RegisterArticleServer(s grpc.ServiceRegistrar, srv ArticleServer) {
	// If the following call pancis, it indicates UnimplementedArticleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Article_ServiceDesc, srv)
}

func _Article_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).List(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_Batch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).Batch(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).Get(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_ByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).ByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_ByTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).ByTitle(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_ViewsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).ViewsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_ViewsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).ViewsBatch(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_UserArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).UserArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_UserArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).UserArticles(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Article_ServiceDesc is the grpc.ServiceDesc for Article service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Article_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spring.v1.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Article_List_Handler,
		},
		{
			MethodName: "Batch",
			Handler:    _Article_Batch_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Article_Get_Handler,
		},
		{
			MethodName: "ByTitle",
			Handler:    _Article_ByTitle_Handler,
		},
		{
			MethodName: "ViewsBatch",
			Handler:    _Article_ViewsBatch_Handler,
		},
		{
			MethodName: "UserArticles",
			Handler:    _Article_UserArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spring/article.proto",
}
