// Server: spring
// Consumers: gozero,fastapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: spring/interaction.proto

package springv1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_spring_interaction_proto protoreflect.FileDescriptor

const file_spring_interaction_proto_rawDesc = "" +
	"\n" +
	"\x18spring/interaction.proto\x12\tspring.v1\x1a\x13common/result.proto2\xe9\x03\n" +
	"\vInteraction\x12:\n" +
	"\rCommentScores\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x127\n" +
	"\n" +
	"LikeCounts\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12:\n" +
	"\rCollectCounts\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x129\n" +
	"\fFollowCounts\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x126\n" +
	"\tUserLikes\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x129\n" +
	"\fUserCollects\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12>\n" +
	"\x11UserFollowerCount\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12;\n" +
	"\x0eCommentsCreate\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB<\n" +
	"$com.hcsy.spring.proto.interaction.v1P\x01Z\x12app/proto/springv1b\x06proto3"

var file_spring_interaction_proto_goTypes = []any{
	(*commonv1.JsonRequest)(nil), // 0: common.v1.JsonRequest
	(*commonv1.Result)(nil),      // 1: common.v1.Result
}
var file_spring_interaction_proto_depIdxs = []int32{
	0, // 0: spring.v1.Interaction.CommentScores:input_type -> common.v1.JsonRequest
	0, // 1: spring.v1.Interaction.LikeCounts:input_type -> common.v1.JsonRequest
	0, // 2: spring.v1.Interaction.CollectCounts:input_type -> common.v1.JsonRequest
	0, // 3: spring.v1.Interaction.FollowCounts:input_type -> common.v1.JsonRequest
	0, // 4: spring.v1.Interaction.UserLikes:input_type -> common.v1.JsonRequest
	0, // 5: spring.v1.Interaction.UserCollects:input_type -> common.v1.JsonRequest
	0, // 6: spring.v1.Interaction.UserFollowerCount:input_type -> common.v1.JsonRequest
	0, // 7: spring.v1.Interaction.CommentsCreate:input_type -> common.v1.JsonRequest
	1, // 8: spring.v1.Interaction.CommentScores:output_type -> common.v1.Result
	1, // 9: spring.v1.Interaction.LikeCounts:output_type -> common.v1.Result
	1, // 10: spring.v1.Interaction.CollectCounts:output_type -> common.v1.Result
	1, // 11: spring.v1.Interaction.FollowCounts:output_type -> common.v1.Result
	1, // 12: spring.v1.Interaction.UserLikes:output_type -> common.v1.Result
	1, // 13: spring.v1.Interaction.UserCollects:output_type -> common.v1.Result
	1, // 14: spring.v1.Interaction.UserFollowerCount:output_type -> common.v1.Result
	1, // 15: spring.v1.Interaction.CommentsCreate:output_type -> common.v1.Result
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spring_interaction_proto_init() }
func file_spring_interaction_proto_init() {
	if File_spring_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spring_interaction_proto_rawDesc), len(file_spring_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spring_interaction_proto_goTypes,
		DependencyIndexes: file_spring_interaction_proto_depIdxs,
	}.Build()
	File_spring_interaction_proto = out.File
	file_spring_interaction_proto_goTypes = nil
	file_spring_interaction_proto_depIdxs = nil
}
