// Server: spring
// Consumers: gozero,fastapi

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: spring/interaction.proto

package springv1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Interaction_CommentScores_FullMethodName     = "/spring.v1.Interaction/CommentScores"
	Interaction_LikeCounts_FullMethodName        = "/spring.v1.Interaction/LikeCounts"
	Interaction_CollectCounts_FullMethodName     = "/spring.v1.Interaction/CollectCounts"
	Interaction_FollowCounts_FullMethodName      = "/spring.v1.Interaction/FollowCounts"
	Interaction_UserLikes_FullMethodName         = "/spring.v1.Interaction/UserLikes"
	Interaction_UserCollects_FullMethodName      = "/spring.v1.Interaction/UserCollects"
	Interaction_UserFollowerCount_FullMethodName = "/spring.v1.Interaction/UserFollowerCount"
	Interaction_CommentsCreate_FullMethodName    = "/spring.v1.Interaction/CommentsCreate"
)

// InteractionClient is the client API for Interaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionClient interface {
	CommentScores(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	LikeCounts(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	CollectCounts(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	FollowCounts(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	UserLikes(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	UserCollects(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	UserFollowerCount(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	CommentsCreate(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type interactionClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionClient(cc grpc.ClientConnInterface) InteractionClient {
	return &interactionClient{cc}
}

func (c *interactionClient) CommentScores(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_CommentScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) LikeCounts(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_LikeCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) CollectCounts(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_CollectCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) FollowCounts(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_FollowCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) UserLikes(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_UserLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) UserCollects(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_UserCollects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) UserFollowerCount(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_UserFollowerCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) CommentsCreate(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Interaction_CommentsCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServer is the server API for Interaction service.
// All implementations must embed UnimplementedInteractionServer
// for forward compatibility.
type InteractionServer interface {
	CommentScores(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	LikeCounts(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	CollectCounts(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	FollowCounts(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	UserLikes(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	UserCollects(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	UserFollowerCount(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	CommentsCreate(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedInteractionServer()
}

// UnimplementedInteractionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServer struct{}

func (UnimplementedInteractionServer) CommentScores(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentScores not implemented")
}
func (UnimplementedInteractionServer) LikeCounts(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeCounts not implemented")
}
func (UnimplementedInteractionServer) CollectCounts(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectCounts not implemented")
}
func (UnimplementedInteractionServer) FollowCounts(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowCounts not implemented")
}
func (UnimplementedInteractionServer) UserLikes(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLikes not implemented")
}
func (UnimplementedInteractionServer) UserCollects(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCollects not implemented")
}
func (UnimplementedInteractionServer) UserFollowerCount(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserFollowerCount not implemented")
}
func (UnimplementedInteractionServer) CommentsCreate(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentsCreate not implemented")
}
func (UnimplementedInteractionServer) mustEmbedUnimplementedInteractionServer() {}
func (UnimplementedInteractionServer) testEmbeddedByValue()                     {}

// UnsafeInteractionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServer will
// result in compilation errors.
type UnsafeInteractionServer interface {
	mustEmbedUnimplementedInteractionServer()
}

func RegisterInteractionServer(s grpc.ServiceRegistrar, srv InteractionServer) {
	// If the following call pancis, it indicates UnimplementedInteractionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Interaction_ServiceDesc, srv)
}

func _Interaction_CommentScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).CommentScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_CommentScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).CommentScores(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_LikeCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).LikeCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_LikeCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).LikeCounts(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_CollectCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).CollectCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_CollectCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).CollectCounts(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_FollowCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).FollowCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_FollowCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).FollowCounts(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_UserLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).UserLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_UserLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).UserLikes(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_UserCollects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).UserCollects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_UserCollects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).UserCollects(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_UserFollowerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).UserFollowerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_UserFollowerCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).UserFollowerCount(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_CommentsCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).CommentsCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_CommentsCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).CommentsCreate(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Interaction_ServiceDesc is the grpc.ServiceDesc for Interaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spring.v1.Interaction",
	HandlerType: (*InteractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommentScores",
			Handler:    _Interaction_CommentScores_Handler,
		},
		{
			MethodName: "LikeCounts",
			Handler:    _Interaction_LikeCounts_Handler,
		},
		{
			MethodName: "CollectCounts",
			Handler:    _Interaction_CollectCounts_Handler,
		},
		{
			MethodName: "FollowCounts",
			Handler:    _Interaction_FollowCounts_Handler,
		},
		{
			MethodName: "UserLikes",
			Handler:    _Interaction_UserLikes_Handler,
		},
		{
			MethodName: "UserCollects",
			Handler:    _Interaction_UserCollects_Handler,
		},
		{
			MethodName: "UserFollowerCount",
			Handler:    _Interaction_UserFollowerCount_Handler,
		},
		{
			MethodName: "CommentsCreate",
			Handler:    _Interaction_CommentsCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spring/interaction.proto",
}
