// Server: spring
// Consumers: gozero,fastapi,nestjs

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: spring/user.proto

package springv1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_spring_user_proto protoreflect.FileDescriptor

const file_spring_user_proto_rawDesc = "" +
	"\n" +
	"\x11spring/user.proto\x12\tspring.v1\x1a\x13common/result.proto2\x83\x03\n" +
	"\x04User\x120\n" +
	"\x03Get\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x122\n" +
	"\x05Batch\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x123\n" +
	"\x06ByName\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x127\n" +
	"\n" +
	"ByGithubId\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x127\n" +
	"\n" +
	"GithubUser\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x124\n" +
	"\aIsAdmin\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x128\n" +
	"\vTokenTicket\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB5\n" +
	"\x1dcom.hcsy.spring.proto.user.v1P\x01Z\x12app/proto/springv1b\x06proto3"

var file_spring_user_proto_goTypes = []any{
	(*commonv1.JsonRequest)(nil), // 0: common.v1.JsonRequest
	(*commonv1.Result)(nil),      // 1: common.v1.Result
}
var file_spring_user_proto_depIdxs = []int32{
	0, // 0: spring.v1.User.Get:input_type -> common.v1.JsonRequest
	0, // 1: spring.v1.User.Batch:input_type -> common.v1.JsonRequest
	0, // 2: spring.v1.User.ByName:input_type -> common.v1.JsonRequest
	0, // 3: spring.v1.User.ByGithubId:input_type -> common.v1.JsonRequest
	0, // 4: spring.v1.User.GithubUser:input_type -> common.v1.JsonRequest
	0, // 5: spring.v1.User.IsAdmin:input_type -> common.v1.JsonRequest
	0, // 6: spring.v1.User.TokenTicket:input_type -> common.v1.JsonRequest
	1, // 7: spring.v1.User.Get:output_type -> common.v1.Result
	1, // 8: spring.v1.User.Batch:output_type -> common.v1.Result
	1, // 9: spring.v1.User.ByName:output_type -> common.v1.Result
	1, // 10: spring.v1.User.ByGithubId:output_type -> common.v1.Result
	1, // 11: spring.v1.User.GithubUser:output_type -> common.v1.Result
	1, // 12: spring.v1.User.IsAdmin:output_type -> common.v1.Result
	1, // 13: spring.v1.User.TokenTicket:output_type -> common.v1.Result
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spring_user_proto_init() }
func file_spring_user_proto_init() {
	if File_spring_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spring_user_proto_rawDesc), len(file_spring_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spring_user_proto_goTypes,
		DependencyIndexes: file_spring_user_proto_depIdxs,
	}.Build()
	File_spring_user_proto = out.File
	file_spring_user_proto_goTypes = nil
	file_spring_user_proto_depIdxs = nil
}
