// Server: fastapi
// Consumers: gozero

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: fastapi/ai_history.proto

package fastapiv1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiHistory_Get_FullMethodName    = "/fastapi.v1.AiHistory/Get"
	AiHistory_Update_FullMethodName = "/fastapi.v1.AiHistory/Update"
	AiHistory_Delete_FullMethodName = "/fastapi.v1.AiHistory/Delete"
)

// AiHistoryClient is the client API for AiHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiHistoryClient interface {
	Get(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	Update(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	Delete(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type aiHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAiHistoryClient(cc grpc.ClientConnInterface) AiHistoryClient {
	return &aiHistoryClient{cc}
}

func (c *aiHistoryClient) Get(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, AiHistory_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiHistoryClient) Update(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, AiHistory_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiHistoryClient) Delete(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, AiHistory_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiHistoryServer is the server API for AiHistory service.
// All implementations must embed UnimplementedAiHistoryServer
// for forward compatibility.
type AiHistoryServer interface {
	Get(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	Update(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	Delete(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedAiHistoryServer()
}

// UnimplementedAiHistoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiHistoryServer struct{}

func (UnimplementedAiHistoryServer) Get(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAiHistoryServer) Update(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAiHistoryServer) Delete(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAiHistoryServer) mustEmbedUnimplementedAiHistoryServer() {}
func (UnimplementedAiHistoryServer) testEmbeddedByValue()                   {}

// UnsafeAiHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiHistoryServer will
// result in compilation errors.
type UnsafeAiHistoryServer interface {
	mustEmbedUnimplementedAiHistoryServer()
}

func RegisterAiHistoryServer(s grpc.ServiceRegistrar, srv AiHistoryServer) {
	// If the following call pancis, it indicates UnimplementedAiHistoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiHistory_ServiceDesc, srv)
}

func _AiHistory_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiHistoryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiHistory_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiHistoryServer).Get(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiHistory_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiHistoryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiHistory_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiHistoryServer).Update(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiHistory_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiHistoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiHistory_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiHistoryServer).Delete(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiHistory_ServiceDesc is the grpc.ServiceDesc for AiHistory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiHistory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastapi.v1.AiHistory",
	HandlerType: (*AiHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _AiHistory_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AiHistory_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AiHistory_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fastapi/ai_history.proto",
}
