// Server: fastapi
// Consumers: gozero

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fastapi/ai_history.proto

package fastapiv1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_fastapi_ai_history_proto protoreflect.FileDescriptor

const file_fastapi_ai_history_proto_rawDesc = "" +
	"\n" +
	"\x18fastapi/ai_history.proto\x12\n" +
	"fastapi.v1\x1a\x13common/result.proto2\xa7\x01\n" +
	"\tAiHistory\x120\n" +
	"\x03Get\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x123\n" +
	"\x06Update\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x123\n" +
	"\x06Delete\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB\x15Z\x13app/proto/fastapiv1b\x06proto3"

var file_fastapi_ai_history_proto_goTypes = []any{
	(*commonv1.JsonRequest)(nil), // 0: common.v1.JsonRequest
	(*commonv1.Result)(nil),      // 1: common.v1.Result
}
var file_fastapi_ai_history_proto_depIdxs = []int32{
	0, // 0: fastapi.v1.AiHistory.Get:input_type -> common.v1.JsonRequest
	0, // 1: fastapi.v1.AiHistory.Update:input_type -> common.v1.JsonRequest
	0, // 2: fastapi.v1.AiHistory.Delete:input_type -> common.v1.JsonRequest
	1, // 3: fastapi.v1.AiHistory.Get:output_type -> common.v1.Result
	1, // 4: fastapi.v1.AiHistory.Update:output_type -> common.v1.Result
	1, // 5: fastapi.v1.AiHistory.Delete:output_type -> common.v1.Result
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fastapi_ai_history_proto_init() }
func file_fastapi_ai_history_proto_init() {
	if File_fastapi_ai_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fastapi_ai_history_proto_rawDesc), len(file_fastapi_ai_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fastapi_ai_history_proto_goTypes,
		DependencyIndexes: file_fastapi_ai_history_proto_depIdxs,
	}.Build()
	File_fastapi_ai_history_proto = out.File
	file_fastapi_ai_history_proto_goTypes = nil
	file_fastapi_ai_history_proto_depIdxs = nil
}
