// Server: fastapi
// Consumers: gozero
// 生成范围：fastapi(Python) + gozero(Go)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fastapi/algorithm.proto

package fastapiv1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_fastapi_algorithm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastapi_algorithm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_fastapi_algorithm_proto_rawDescGZIP(), []int{0}
}

var File_fastapi_algorithm_proto protoreflect.FileDescriptor

const file_fastapi_algorithm_proto_rawDesc = "" +
	"\n" +
	"\x17fastapi/algorithm.proto\x12\n" +
	"fastapi.v1\x1a\x13common/result.proto\"\x0e\n" +
	"\fEmptyRequest2\xd2\x01\n" +
	"\tAlgorithm\x12?\n" +
	"\x10GetSearchWeights\x12\x18.fastapi.v1.EmptyRequest\x1a\x11.common.v1.Result\x12>\n" +
	"\x0fGetSearchScript\x12\x18.fastapi.v1.EmptyRequest\x1a\x11.common.v1.Result\x12D\n" +
	"\x15GetSearchScriptParams\x12\x18.fastapi.v1.EmptyRequest\x1a\x11.common.v1.ResultB9\n" +
	" com.hcsy.spring.proto.fastapi.v1P\x01Z\x13app/proto/fastapiv1b\x06proto3"

var (
	file_fastapi_algorithm_proto_rawDescOnce sync.Once
	file_fastapi_algorithm_proto_rawDescData []byte
)

func file_fastapi_algorithm_proto_rawDescGZIP() []byte {
	file_fastapi_algorithm_proto_rawDescOnce.Do(func() {
		file_fastapi_algorithm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fastapi_algorithm_proto_rawDesc), len(file_fastapi_algorithm_proto_rawDesc)))
	})
	return file_fastapi_algorithm_proto_rawDescData
}

var file_fastapi_algorithm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fastapi_algorithm_proto_goTypes = []any{
	(*EmptyRequest)(nil),    // 0: fastapi.v1.EmptyRequest
	(*commonv1.Result)(nil), // 1: common.v1.Result
}
var file_fastapi_algorithm_proto_depIdxs = []int32{
	0, // 0: fastapi.v1.Algorithm.GetSearchWeights:input_type -> fastapi.v1.EmptyRequest
	0, // 1: fastapi.v1.Algorithm.GetSearchScript:input_type -> fastapi.v1.EmptyRequest
	0, // 2: fastapi.v1.Algorithm.GetSearchScriptParams:input_type -> fastapi.v1.EmptyRequest
	1, // 3: fastapi.v1.Algorithm.GetSearchWeights:output_type -> common.v1.Result
	1, // 4: fastapi.v1.Algorithm.GetSearchScript:output_type -> common.v1.Result
	1, // 5: fastapi.v1.Algorithm.GetSearchScriptParams:output_type -> common.v1.Result
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fastapi_algorithm_proto_init() }
func file_fastapi_algorithm_proto_init() {
	if File_fastapi_algorithm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fastapi_algorithm_proto_rawDesc), len(file_fastapi_algorithm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fastapi_algorithm_proto_goTypes,
		DependencyIndexes: file_fastapi_algorithm_proto_depIdxs,
		MessageInfos:      file_fastapi_algorithm_proto_msgTypes,
	}.Build()
	File_fastapi_algorithm_proto = out.File
	file_fastapi_algorithm_proto_goTypes = nil
	file_fastapi_algorithm_proto_depIdxs = nil
}
