// Server: fastapi
// Consumers: gozero
// 生成范围：fastapi(Python) + gozero(Go)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: fastapi/algorithm.proto

package fastapiv1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Algorithm_GetSearchWeights_FullMethodName      = "/fastapi.v1.Algorithm/GetSearchWeights"
	Algorithm_GetSearchScript_FullMethodName       = "/fastapi.v1.Algorithm/GetSearchScript"
	Algorithm_GetSearchScriptParams_FullMethodName = "/fastapi.v1.Algorithm/GetSearchScriptParams"
)

// AlgorithmClient is the client API for Algorithm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlgorithmClient interface {
	GetSearchWeights(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	GetSearchScript(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	GetSearchScriptParams(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type algorithmClient struct {
	cc grpc.ClientConnInterface
}

func NewAlgorithmClient(cc grpc.ClientConnInterface) AlgorithmClient {
	return &algorithmClient{cc}
}

func (c *algorithmClient) GetSearchWeights(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Algorithm_GetSearchWeights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmClient) GetSearchScript(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Algorithm_GetSearchScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmClient) GetSearchScriptParams(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Algorithm_GetSearchScriptParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorithmServer is the server API for Algorithm service.
// All implementations must embed UnimplementedAlgorithmServer
// for forward compatibility.
type AlgorithmServer interface {
	GetSearchWeights(context.Context, *EmptyRequest) (*commonv1.Result, error)
	GetSearchScript(context.Context, *EmptyRequest) (*commonv1.Result, error)
	GetSearchScriptParams(context.Context, *EmptyRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedAlgorithmServer()
}

// UnimplementedAlgorithmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlgorithmServer struct{}

func (UnimplementedAlgorithmServer) GetSearchWeights(context.Context, *EmptyRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchWeights not implemented")
}
func (UnimplementedAlgorithmServer) GetSearchScript(context.Context, *EmptyRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchScript not implemented")
}
func (UnimplementedAlgorithmServer) GetSearchScriptParams(context.Context, *EmptyRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchScriptParams not implemented")
}
func (UnimplementedAlgorithmServer) mustEmbedUnimplementedAlgorithmServer() {}
func (UnimplementedAlgorithmServer) testEmbeddedByValue()                   {}

// UnsafeAlgorithmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlgorithmServer will
// result in compilation errors.
type UnsafeAlgorithmServer interface {
	mustEmbedUnimplementedAlgorithmServer()
}

func RegisterAlgorithmServer(s grpc.ServiceRegistrar, srv AlgorithmServer) {
	// If the following call pancis, it indicates UnimplementedAlgorithmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Algorithm_ServiceDesc, srv)
}

func _Algorithm_GetSearchWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmServer).GetSearchWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Algorithm_GetSearchWeights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmServer).GetSearchWeights(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorithm_GetSearchScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmServer).GetSearchScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Algorithm_GetSearchScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmServer).GetSearchScript(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorithm_GetSearchScriptParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmServer).GetSearchScriptParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Algorithm_GetSearchScriptParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmServer).GetSearchScriptParams(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Algorithm_ServiceDesc is the grpc.ServiceDesc for Algorithm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Algorithm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastapi.v1.Algorithm",
	HandlerType: (*AlgorithmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSearchWeights",
			Handler:    _Algorithm_GetSearchWeights_Handler,
		},
		{
			MethodName: "GetSearchScript",
			Handler:    _Algorithm_GetSearchScript_Handler,
		},
		{
			MethodName: "GetSearchScriptParams",
			Handler:    _Algorithm_GetSearchScriptParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fastapi/algorithm.proto",
}
