// Server: fastapi
// Consumers: gozero
// 生成范围：fastapi(Python) + gozero(Go)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: fastapi/search_enhance.proto

package fastapiv1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchEnhance_EnhanceGraph_FullMethodName  = "/fastapi.v1.SearchEnhance/EnhanceGraph"
	SearchEnhance_EnhanceVector_FullMethodName = "/fastapi.v1.SearchEnhance/EnhanceVector"
)

// SearchEnhanceClient is the client API for SearchEnhance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchEnhanceClient interface {
	EnhanceGraph(ctx context.Context, in *GraphEnhanceRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	EnhanceVector(ctx context.Context, in *VectorEnhanceRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type searchEnhanceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchEnhanceClient(cc grpc.ClientConnInterface) SearchEnhanceClient {
	return &searchEnhanceClient{cc}
}

func (c *searchEnhanceClient) EnhanceGraph(ctx context.Context, in *GraphEnhanceRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, SearchEnhance_EnhanceGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchEnhanceClient) EnhanceVector(ctx context.Context, in *VectorEnhanceRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, SearchEnhance_EnhanceVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchEnhanceServer is the server API for SearchEnhance service.
// All implementations must embed UnimplementedSearchEnhanceServer
// for forward compatibility.
type SearchEnhanceServer interface {
	EnhanceGraph(context.Context, *GraphEnhanceRequest) (*commonv1.Result, error)
	EnhanceVector(context.Context, *VectorEnhanceRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedSearchEnhanceServer()
}

// UnimplementedSearchEnhanceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchEnhanceServer struct{}

func (UnimplementedSearchEnhanceServer) EnhanceGraph(context.Context, *GraphEnhanceRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnhanceGraph not implemented")
}
func (UnimplementedSearchEnhanceServer) EnhanceVector(context.Context, *VectorEnhanceRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnhanceVector not implemented")
}
func (UnimplementedSearchEnhanceServer) mustEmbedUnimplementedSearchEnhanceServer() {}
func (UnimplementedSearchEnhanceServer) testEmbeddedByValue()                       {}

// UnsafeSearchEnhanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchEnhanceServer will
// result in compilation errors.
type UnsafeSearchEnhanceServer interface {
	mustEmbedUnimplementedSearchEnhanceServer()
}

func RegisterSearchEnhanceServer(s grpc.ServiceRegistrar, srv SearchEnhanceServer) {
	// If the following call pancis, it indicates UnimplementedSearchEnhanceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchEnhance_ServiceDesc, srv)
}

func _SearchEnhance_EnhanceGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphEnhanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchEnhanceServer).EnhanceGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchEnhance_EnhanceGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchEnhanceServer).EnhanceGraph(ctx, req.(*GraphEnhanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchEnhance_EnhanceVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorEnhanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchEnhanceServer).EnhanceVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchEnhance_EnhanceVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchEnhanceServer).EnhanceVector(ctx, req.(*VectorEnhanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchEnhance_ServiceDesc is the grpc.ServiceDesc for SearchEnhance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchEnhance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastapi.v1.SearchEnhance",
	HandlerType: (*SearchEnhanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnhanceGraph",
			Handler:    _SearchEnhance_EnhanceGraph_Handler,
		},
		{
			MethodName: "EnhanceVector",
			Handler:    _SearchEnhance_EnhanceVector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fastapi/search_enhance.proto",
}
