// Server: fastapi
// Consumers: gozero
// 生成范围：fastapi(Python) + gozero(Go)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fastapi/search_enhance.proto

package fastapiv1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphEnhanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword         string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ArticleIds      []int64                `protobuf:"varint,3,rep,packed,name=article_ids,json=articleIds,proto3" json:"article_ids,omitempty"`
	CategoryName    string                 `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	SubCategoryName string                 `protobuf:"bytes,5,opt,name=sub_category_name,json=subCategoryName,proto3" json:"sub_category_name,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Limit           int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Mode            string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GraphEnhanceRequest) Reset() {
	*x = GraphEnhanceRequest{}
	mi := &file_fastapi_search_enhance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEnhanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEnhanceRequest) ProtoMessage() {}

func (x *GraphEnhanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastapi_search_enhance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEnhanceRequest.ProtoReflect.Descriptor instead.
func (*GraphEnhanceRequest) Descriptor() ([]byte, []int) {
	return file_fastapi_search_enhance_proto_rawDescGZIP(), []int{0}
}

func (x *GraphEnhanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GraphEnhanceRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GraphEnhanceRequest) GetArticleIds() []int64 {
	if x != nil {
		return x.ArticleIds
	}
	return nil
}

func (x *GraphEnhanceRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *GraphEnhanceRequest) GetSubCategoryName() string {
	if x != nil {
		return x.SubCategoryName
	}
	return ""
}

func (x *GraphEnhanceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GraphEnhanceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GraphEnhanceRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type VectorEnhanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword         string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ArticleIds      []int64                `protobuf:"varint,3,rep,packed,name=article_ids,json=articleIds,proto3" json:"article_ids,omitempty"`
	CategoryName    string                 `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	SubCategoryName string                 `protobuf:"bytes,5,opt,name=sub_category_name,json=subCategoryName,proto3" json:"sub_category_name,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Limit           int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	TopK            int32                  `protobuf:"varint,8,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Mode            string                 `protobuf:"bytes,9,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VectorEnhanceRequest) Reset() {
	*x = VectorEnhanceRequest{}
	mi := &file_fastapi_search_enhance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorEnhanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorEnhanceRequest) ProtoMessage() {}

func (x *VectorEnhanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastapi_search_enhance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorEnhanceRequest.ProtoReflect.Descriptor instead.
func (*VectorEnhanceRequest) Descriptor() ([]byte, []int) {
	return file_fastapi_search_enhance_proto_rawDescGZIP(), []int{1}
}

func (x *VectorEnhanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VectorEnhanceRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *VectorEnhanceRequest) GetArticleIds() []int64 {
	if x != nil {
		return x.ArticleIds
	}
	return nil
}

func (x *VectorEnhanceRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *VectorEnhanceRequest) GetSubCategoryName() string {
	if x != nil {
		return x.SubCategoryName
	}
	return ""
}

func (x *VectorEnhanceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *VectorEnhanceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *VectorEnhanceRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *VectorEnhanceRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

var File_fastapi_search_enhance_proto protoreflect.FileDescriptor

const file_fastapi_search_enhance_proto_rawDesc = "" +
	"\n" +
	"\x1cfastapi/search_enhance.proto\x12\n" +
	"fastapi.v1\x1a\x13common/result.proto\"\xf8\x01\n" +
	"\x13GraphEnhanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1f\n" +
	"\varticle_ids\x18\x03 \x03(\x03R\n" +
	"articleIds\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12*\n" +
	"\x11sub_category_name\x18\x05 \x01(\tR\x0fsubCategoryName\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\"\x8e\x02\n" +
	"\x14VectorEnhanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1f\n" +
	"\varticle_ids\x18\x03 \x03(\x03R\n" +
	"articleIds\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12*\n" +
	"\x11sub_category_name\x18\x05 \x01(\tR\x0fsubCategoryName\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x13\n" +
	"\x05top_k\x18\b \x01(\x05R\x04topK\x12\x12\n" +
	"\x04mode\x18\t \x01(\tR\x04mode2\x99\x01\n" +
	"\rSearchEnhance\x12B\n" +
	"\fEnhanceGraph\x12\x1f.fastapi.v1.GraphEnhanceRequest\x1a\x11.common.v1.Result\x12D\n" +
	"\rEnhanceVector\x12 .fastapi.v1.VectorEnhanceRequest\x1a\x11.common.v1.ResultB9\n" +
	" com.hcsy.spring.proto.fastapi.v1P\x01Z\x13app/proto/fastapiv1b\x06proto3"

var (
	file_fastapi_search_enhance_proto_rawDescOnce sync.Once
	file_fastapi_search_enhance_proto_rawDescData []byte
)

func file_fastapi_search_enhance_proto_rawDescGZIP() []byte {
	file_fastapi_search_enhance_proto_rawDescOnce.Do(func() {
		file_fastapi_search_enhance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fastapi_search_enhance_proto_rawDesc), len(file_fastapi_search_enhance_proto_rawDesc)))
	})
	return file_fastapi_search_enhance_proto_rawDescData
}

var file_fastapi_search_enhance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fastapi_search_enhance_proto_goTypes = []any{
	(*GraphEnhanceRequest)(nil),  // 0: fastapi.v1.GraphEnhanceRequest
	(*VectorEnhanceRequest)(nil), // 1: fastapi.v1.VectorEnhanceRequest
	(*commonv1.Result)(nil),      // 2: common.v1.Result
}
var file_fastapi_search_enhance_proto_depIdxs = []int32{
	0, // 0: fastapi.v1.SearchEnhance.EnhanceGraph:input_type -> fastapi.v1.GraphEnhanceRequest
	1, // 1: fastapi.v1.SearchEnhance.EnhanceVector:input_type -> fastapi.v1.VectorEnhanceRequest
	2, // 2: fastapi.v1.SearchEnhance.EnhanceGraph:output_type -> common.v1.Result
	2, // 3: fastapi.v1.SearchEnhance.EnhanceVector:output_type -> common.v1.Result
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fastapi_search_enhance_proto_init() }
func file_fastapi_search_enhance_proto_init() {
	if File_fastapi_search_enhance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fastapi_search_enhance_proto_rawDesc), len(file_fastapi_search_enhance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fastapi_search_enhance_proto_goTypes,
		DependencyIndexes: file_fastapi_search_enhance_proto_depIdxs,
		MessageInfos:      file_fastapi_search_enhance_proto_msgTypes,
	}.Build()
	File_fastapi_search_enhance_proto = out.File
	file_fastapi_search_enhance_proto_goTypes = nil
	file_fastapi_search_enhance_proto_depIdxs = nil
}
