// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spring/user.proto

package com.hcsy.spring.proto.user.v1;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021spring/user.proto\022\tspring.v1\032\023common/r" +
      "esult.proto2\203\003\n\004User\0220\n\003Get\022\026.common.v1." +
      "JsonRequest\032\021.common.v1.Result\0222\n\005Batch\022" +
      "\026.common.v1.JsonRequest\032\021.common.v1.Resu" +
      "lt\0223\n\006ByName\022\026.common.v1.JsonRequest\032\021.c" +
      "ommon.v1.Result\0227\n\nByGithubId\022\026.common.v" +
      "1.JsonRequest\032\021.common.v1.Result\0227\n\nGith" +
      "ubUser\022\026.common.v1.JsonRequest\032\021.common." +
      "v1.Result\0224\n\007IsAdmin\022\026.common.v1.JsonReq" +
      "uest\032\021.common.v1.Result\0228\n\013TokenTicket\022\026" +
      ".common.v1.JsonRequest\032\021.common.v1.Resul" +
      "tB5\n\035com.hcsy.spring.proto.user.v1P\001Z\022ap" +
      "p/proto/springv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
