// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v3.21.12
// source: spring/article.proto

/* eslint-disable */
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { JsonRequest, Result } from "../common/result";

export const protobufPackage = "spring.v1";

/**
 * Server: spring
 * Consumers: gozero,fastapi,nestjs
 */

export const SPRING_V1_PACKAGE_NAME = "spring.v1";

export interface ArticleClient {
  list(request: JsonRequest): Observable<Result>;

  batch(request: JsonRequest): Observable<Result>;

  get(request: JsonRequest): Observable<Result>;

  byTitle(request: JsonRequest): Observable<Result>;

  viewsBatch(request: JsonRequest): Observable<Result>;

  userArticles(request: JsonRequest): Observable<Result>;
}

export interface ArticleController {
  list(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  batch(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  get(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  byTitle(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  viewsBatch(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  userArticles(request: JsonRequest): Promise<Result> | Observable<Result> | Result;
}

export function ArticleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["list", "batch", "get", "byTitle", "viewsBatch", "userArticles"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Article", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Article", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ARTICLE_SERVICE_NAME = "Article";

export type ArticleService = typeof ArticleService;
export const ArticleService = {
  list: {
    path: "/spring.v1.Article/List" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  batch: {
    path: "/spring.v1.Article/Batch" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  get: {
    path: "/spring.v1.Article/Get" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  byTitle: {
    path: "/spring.v1.Article/ByTitle" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  viewsBatch: {
    path: "/spring.v1.Article/ViewsBatch" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  userArticles: {
    path: "/spring.v1.Article/UserArticles" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
} as const;

export interface ArticleServer extends UntypedServiceImplementation {
  list: handleUnaryCall<JsonRequest, Result>;
  batch: handleUnaryCall<JsonRequest, Result>;
  get: handleUnaryCall<JsonRequest, Result>;
  byTitle: handleUnaryCall<JsonRequest, Result>;
  viewsBatch: handleUnaryCall<JsonRequest, Result>;
  userArticles: handleUnaryCall<JsonRequest, Result>;
}
