// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v3.21.12
// source: spring/statistics.proto

/* eslint-disable */
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { JsonRequest, Result } from "../common/result";

export const protobufPackage = "spring.v1";

/**
 * Server: spring
 * Consumers: fastapi,nestjs
 */

export const SPRING_V1_PACKAGE_NAME = "spring.v1";

export interface StatisticsClient {
  article(request: JsonRequest): Observable<Result>;

  interaction(request: JsonRequest): Observable<Result>;

  follow(request: JsonRequest): Observable<Result>;

  userPortrait(request: JsonRequest): Observable<Result>;
}

export interface StatisticsController {
  article(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  interaction(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  follow(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  userPortrait(request: JsonRequest): Promise<Result> | Observable<Result> | Result;
}

export function StatisticsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["article", "interaction", "follow", "userPortrait"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Statistics", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Statistics", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STATISTICS_SERVICE_NAME = "Statistics";

export type StatisticsService = typeof StatisticsService;
export const StatisticsService = {
  article: {
    path: "/spring.v1.Statistics/Article" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  interaction: {
    path: "/spring.v1.Statistics/Interaction" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  follow: {
    path: "/spring.v1.Statistics/Follow" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  userPortrait: {
    path: "/spring.v1.Statistics/UserPortrait" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
} as const;

export interface StatisticsServer extends UntypedServiceImplementation {
  article: handleUnaryCall<JsonRequest, Result>;
  interaction: handleUnaryCall<JsonRequest, Result>;
  follow: handleUnaryCall<JsonRequest, Result>;
  userPortrait: handleUnaryCall<JsonRequest, Result>;
}
