// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v3.21.12
// source: spring/user.proto

/* eslint-disable */
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { JsonRequest, Result } from "../common/result";

export const protobufPackage = "spring.v1";

/**
 * Server: spring
 * Consumers: gozero,fastapi,nestjs
 */

export const SPRING_V1_PACKAGE_NAME = "spring.v1";

export interface UserClient {
  get(request: JsonRequest): Observable<Result>;

  batch(request: JsonRequest): Observable<Result>;

  byName(request: JsonRequest): Observable<Result>;

  byGithubId(request: JsonRequest): Observable<Result>;

  githubUser(request: JsonRequest): Observable<Result>;

  isAdmin(request: JsonRequest): Observable<Result>;

  tokenTicket(request: JsonRequest): Observable<Result>;
}

export interface UserController {
  get(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  batch(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  byName(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  byGithubId(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  githubUser(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  isAdmin(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  tokenTicket(request: JsonRequest): Promise<Result> | Observable<Result> | Result;
}

export function UserControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["get", "batch", "byName", "byGithubId", "githubUser", "isAdmin", "tokenTicket"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("User", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("User", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "User";

export type UserService = typeof UserService;
export const UserService = {
  get: {
    path: "/spring.v1.User/Get" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  batch: {
    path: "/spring.v1.User/Batch" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  byName: {
    path: "/spring.v1.User/ByName" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  byGithubId: {
    path: "/spring.v1.User/ByGithubId" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  githubUser: {
    path: "/spring.v1.User/GithubUser" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  isAdmin: {
    path: "/spring.v1.User/IsAdmin" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  tokenTicket: {
    path: "/spring.v1.User/TokenTicket" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
} as const;

export interface UserServer extends UntypedServiceImplementation {
  get: handleUnaryCall<JsonRequest, Result>;
  batch: handleUnaryCall<JsonRequest, Result>;
  byName: handleUnaryCall<JsonRequest, Result>;
  byGithubId: handleUnaryCall<JsonRequest, Result>;
  githubUser: handleUnaryCall<JsonRequest, Result>;
  isAdmin: handleUnaryCall<JsonRequest, Result>;
  tokenTicket: handleUnaryCall<JsonRequest, Result>;
}
