"""
错误标识类 — 传给 BusinessException 的 error 参数
"""


class ErrorCodes:
    # ===== 400 Bad Request =====
    ERROR_PARAM_PARSE_FAILED: str = "PARAM_PARSE_FAILED"
    ERROR_COLLECTION_NAME_REQUIRED: str = "COLLECTION_NAME_REQUIRED"

    # ===== 401 Unauthorized =====
    ERROR_USER_NOT_LOGIN: str = "USER_NOT_LOGIN"
    ERROR_INTERNAL_TOKEN_MISSING: str = "INTERNAL_TOKEN_MISSING"
    ERROR_INTERNAL_TOKEN_INVALID: str = "INTERNAL_TOKEN_INVALID"
    ERROR_INTERNAL_TOKEN_EXPIRED: str = "INTERNAL_TOKEN_EXPIRED"

    # ===== 403 Forbidden =====
    ERROR_PERMISSION_CHECK_FAILED: str = "PERMISSION_CHECK_FAILED"
    ERROR_NO_ADMIN_PERMISSION: str = "NO_ADMIN_PERMISSION"
    ERROR_USER_NO_ADMIN_PERMISSION: str = "USER_NO_ADMIN_PERMISSION"
    ERROR_INTENT_ROUTER_NO_PERMISSION: str = "INTENT_ROUTER_NO_PERMISSION"
    ERROR_INTERNAL_TOKEN_SERVICE_MISMATCH: str = "INTERNAL_TOKEN_SERVICE_MISMATCH"

    # ===== 404 Not Found =====
    ERROR_USER_NOT_FOUND: str = "USER_NOT_FOUND"
    ERROR_ARTICLE_NOT_FOUND: str = "ARTICLE_NOT_FOUND"
    ERROR_NO_RELEVANT_ARTICLES: str = "NO_RELEVANT_ARTICLES"
    ERROR_AI_CHAT_NO_INSTANCE: str = "AI_CHAT_NO_INSTANCE"

    # ===== 429 Too Many Requests =====
    ERROR_GEMINI_QUOTA_EXCEEDED: str = "GEMINI_QUOTA_EXCEEDED"
    ERROR_GEMINI_RATE_LIMIT_EXCEEDED: str = "GEMINI_RATE_LIMIT_EXCEEDED"
    ERROR_GPT_RATE_LIMIT_EXCEEDED: str = "GPT_RATE_LIMIT_EXCEEDED"

    # ===== 500 Internal Server Error =====
    ERROR_FASTAPI_SERVER_ERROR: str = "FASTAPI_SERVER_ERROR"
    ERROR_DEEPSEEK_CALL_FAILED: str = "DEEPSEEK_CALL_FAILED"
    ERROR_GEMINI_CALL_FAILED: str = "GEMINI_CALL_FAILED"
    ERROR_GPT_CALL_FAILED: str = "GPT_CALL_FAILED"
    ERROR_SERVICE_CALL_FAILED: str = "SERVICE_CALL_FAILED"
    ERROR_INTERNAL_TOKEN_SECRET_NOT_NULL: str = "INTERNAL_TOKEN_SECRET_NOT_NULL"

    # ===== 503 Service Unavailable =====
    ERROR_RABBITMQ_CLIENT_NOT_INITIALIZED: str = "RABBITMQ_CLIENT_NOT_INITIALIZED"
    ERROR_RABBITMQ_NOT_CONNECTED: str = "RABBITMQ_NOT_CONNECTED"
