basePath: /
host: localhost:8082
info:
  contact: {}
  description: 这是demo项目的Gin部分的Swagger文档集成
  title: Gin部分的Swagger文档集成
  version: "1.0"
paths:
  /api_gin/gin:
    get:
      description: 输出欢迎信息
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Gin自己的测试
      tags:
      - 测试
  /api_gin/nestjs:
    get:
      description: 输出欢迎信息
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 调用NestJS的测试
      tags:
      - 测试
  /api_gin/spring:
    get:
      description: 输出欢迎信息
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 调用Spring的测试
      tags:
      - 测试
  /users:
    get:
      description: 获取用户列表
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户信息
      tags:
      - 用户
swagger: "2.0"
