// Server: nestjs
// Consumers: gozero,fastapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: nestjs/log.proto

package nestjsv1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_nestjs_log_proto protoreflect.FileDescriptor

const file_nestjs_log_proto_rawDesc = "" +
	"\n" +
	"\x10nestjs/log.proto\x12\tnestjs.v1\x1a\x13common/result.proto2\xb8\x02\n" +
	"\x03Log\x12:\n" +
	"\rSearchHistory\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12=\n" +
	"\x10ViewDistribution\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12;\n" +
	"\x0eSearchKeywords\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12<\n" +
	"\x0fApiAverageSpeed\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12;\n" +
	"\x0eApiCalledCount\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB2\n" +
	"\x1ccom.hcsy.nestjs.proto.log.v1Z\x12app/proto/nestjsv1b\x06proto3"

var file_nestjs_log_proto_goTypes = []any{
	(*commonv1.JsonRequest)(nil), // 0: common.v1.JsonRequest
	(*commonv1.Result)(nil),      // 1: common.v1.Result
}
var file_nestjs_log_proto_depIdxs = []int32{
	0, // 0: nestjs.v1.Log.SearchHistory:input_type -> common.v1.JsonRequest
	0, // 1: nestjs.v1.Log.ViewDistribution:input_type -> common.v1.JsonRequest
	0, // 2: nestjs.v1.Log.SearchKeywords:input_type -> common.v1.JsonRequest
	0, // 3: nestjs.v1.Log.ApiAverageSpeed:input_type -> common.v1.JsonRequest
	0, // 4: nestjs.v1.Log.ApiCalledCount:input_type -> common.v1.JsonRequest
	1, // 5: nestjs.v1.Log.SearchHistory:output_type -> common.v1.Result
	1, // 6: nestjs.v1.Log.ViewDistribution:output_type -> common.v1.Result
	1, // 7: nestjs.v1.Log.SearchKeywords:output_type -> common.v1.Result
	1, // 8: nestjs.v1.Log.ApiAverageSpeed:output_type -> common.v1.Result
	1, // 9: nestjs.v1.Log.ApiCalledCount:output_type -> common.v1.Result
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nestjs_log_proto_init() }
func file_nestjs_log_proto_init() {
	if File_nestjs_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nestjs_log_proto_rawDesc), len(file_nestjs_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nestjs_log_proto_goTypes,
		DependencyIndexes: file_nestjs_log_proto_depIdxs,
	}.Build()
	File_nestjs_log_proto = out.File
	file_nestjs_log_proto_goTypes = nil
	file_nestjs_log_proto_depIdxs = nil
}
