// Server: nestjs
// Consumers: gozero,fastapi

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: nestjs/log.proto

package nestjsv1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Log_SearchHistory_FullMethodName    = "/nestjs.v1.Log/SearchHistory"
	Log_ViewDistribution_FullMethodName = "/nestjs.v1.Log/ViewDistribution"
	Log_SearchKeywords_FullMethodName   = "/nestjs.v1.Log/SearchKeywords"
	Log_ApiAverageSpeed_FullMethodName  = "/nestjs.v1.Log/ApiAverageSpeed"
	Log_ApiCalledCount_FullMethodName   = "/nestjs.v1.Log/ApiCalledCount"
)

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogClient interface {
	SearchHistory(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	ViewDistribution(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	SearchKeywords(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	ApiAverageSpeed(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	ApiCalledCount(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type logClient struct {
	cc grpc.ClientConnInterface
}

func NewLogClient(cc grpc.ClientConnInterface) LogClient {
	return &logClient{cc}
}

func (c *logClient) SearchHistory(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Log_SearchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) ViewDistribution(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Log_ViewDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) SearchKeywords(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Log_SearchKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) ApiAverageSpeed(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Log_ApiAverageSpeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) ApiCalledCount(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, Log_ApiCalledCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
// All implementations must embed UnimplementedLogServer
// for forward compatibility.
type LogServer interface {
	SearchHistory(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	ViewDistribution(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	SearchKeywords(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	ApiAverageSpeed(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	ApiCalledCount(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedLogServer()
}

// UnimplementedLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServer struct{}

func (UnimplementedLogServer) SearchHistory(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHistory not implemented")
}
func (UnimplementedLogServer) ViewDistribution(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewDistribution not implemented")
}
func (UnimplementedLogServer) SearchKeywords(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchKeywords not implemented")
}
func (UnimplementedLogServer) ApiAverageSpeed(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiAverageSpeed not implemented")
}
func (UnimplementedLogServer) ApiCalledCount(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiCalledCount not implemented")
}
func (UnimplementedLogServer) mustEmbedUnimplementedLogServer() {}
func (UnimplementedLogServer) testEmbeddedByValue()             {}

// UnsafeLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServer will
// result in compilation errors.
type UnsafeLogServer interface {
	mustEmbedUnimplementedLogServer()
}

func RegisterLogServer(s grpc.ServiceRegistrar, srv LogServer) {
	// If the following call pancis, it indicates UnimplementedLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Log_ServiceDesc, srv)
}

func _Log_SearchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).SearchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_SearchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).SearchHistory(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_ViewDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).ViewDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_ViewDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).ViewDistribution(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_SearchKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).SearchKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_SearchKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).SearchKeywords(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_ApiAverageSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).ApiAverageSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_ApiAverageSpeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).ApiAverageSpeed(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_ApiCalledCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).ApiCalledCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_ApiCalledCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).ApiCalledCount(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Log_ServiceDesc is the grpc.ServiceDesc for Log service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Log_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nestjs.v1.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchHistory",
			Handler:    _Log_SearchHistory_Handler,
		},
		{
			MethodName: "ViewDistribution",
			Handler:    _Log_ViewDistribution_Handler,
		},
		{
			MethodName: "SearchKeywords",
			Handler:    _Log_SearchKeywords_Handler,
		},
		{
			MethodName: "ApiAverageSpeed",
			Handler:    _Log_ApiAverageSpeed_Handler,
		},
		{
			MethodName: "ApiCalledCount",
			Handler:    _Log_ApiCalledCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nestjs/log.proto",
}
