// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	chat "app/internal/handler/chat"
	search "app/internal/handler/search"
	task "app/internal/handler/task"
	test "app/internal/handler/test"
	"app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware, serverCtx.RecoveryMiddleware},
			[]rest.Route{
				{
					// SSE消息通知连接
					Method:  http.MethodGet,
					Path:    "/sse/chat",
					Handler: chat.ChatSSEHandler(serverCtx),
				},
				{
					// WebSocket聊天连接
					Method:  http.MethodGet,
					Path:    "/ws/chat",
					Handler: chat.ChatWebsocketHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware, serverCtx.RecoveryMiddleware},
			[]rest.Route{
				{
					// 获取用户的所有未读消息数
					Method:  http.MethodPost,
					Path:    "/all-unread-counts",
					Handler: chat.ChatGetAllUnreadCountsHandler(serverCtx),
				},
				{
					// 获取聊天历史
					Method:  http.MethodPost,
					Path:    "/history",
					Handler: chat.ChatGetHistoryHandler(serverCtx),
				},
				{
					// 手动加入聊天队列
					Method:  http.MethodPost,
					Path:    "/join",
					Handler: chat.ChatJoinQueueHandler(serverCtx),
				},
				{
					// 手动离开聊天队列
					Method:  http.MethodPost,
					Path:    "/leave",
					Handler: chat.ChatLeaveQueueHandler(serverCtx),
				},
				{
					// 获取队列状态
					Method:  http.MethodGet,
					Path:    "/queue",
					Handler: chat.ChatGetQueueStatusHandler(serverCtx),
				},
				{
					// 发送聊天消息
					Method:  http.MethodPost,
					Path:    "/send",
					Handler: chat.ChatSendMessageHandler(serverCtx),
				},
				{
					// 获取两个用户间的未读消息数
					Method:  http.MethodPost,
					Path:    "/unread-count",
					Handler: chat.ChatGetUnreadCountHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/user-chat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware, serverCtx.RecoveryMiddleware},
			[]rest.Route{
				{
					// 搜索文章
					Method:  http.MethodGet,
					Path:    "/",
					Handler: search.SearchArticlesHandler(serverCtx),
				},
				{
					// 获取用户搜索历史
					Method:  http.MethodGet,
					Path:    "/history/:user_id",
					Handler: search.GetSearchHistoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/search"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware, serverCtx.RecoveryMiddleware},
			[]rest.Route{
				{
					// 测试GoZero服务
					Method:  http.MethodGet,
					Path:    "/gozero",
					Handler: test.TestGoZeroHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/test"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware, serverCtx.RecoveryMiddleware, serverCtx.InternalServiceMiddleware},
			[]rest.Route{
				{
					// 手动触发同步ES任务
					Method:  http.MethodPost,
					Path:    "/syncer",
					Handler: task.SyncESHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/task"),
	)
}
