// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spring/category.proto

package com.hcsy.spring.proto.category.v1;

public final class CategoryOuterClass {
  private CategoryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025spring/category.proto\022\tspring.v1\032\023comm" +
      "on/result.proto2\236\002\n\010Category\0222\n\005Batch\022\026." +
      "common.v1.JsonRequest\032\021.common.v1.Result" +
      "\0225\n\010SubBatch\022\026.common.v1.JsonRequest\032\021.c" +
      "ommon.v1.Result\0220\n\003All\022\026.common.v1.JsonR" +
      "equest\032\021.common.v1.Result\022:\n\rSubWithPare" +
      "nt\022\026.common.v1.JsonRequest\032\021.common.v1.R" +
      "esult\0229\n\014ReferenceSub\022\026.common.v1.JsonRe" +
      "quest\032\021.common.v1.ResultB7\n!com.hcsy.spr" +
      "ing.proto.category.v1Z\022app/proto/springv" +
      "1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
