// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package categoryReference

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"app/model"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	categoryReferenceFieldNames          = builder.RawFieldNames(&CategoryReference{})
	categoryReferenceRows                = strings.Join(categoryReferenceFieldNames, ",")
	categoryReferenceRowsExpectAutoSet   = strings.Join(stringx.Remove(categoryReferenceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	categoryReferenceRowsWithPlaceHolder = strings.Join(stringx.Remove(categoryReferenceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	categoryReferenceModel interface {
		Insert(ctx context.Context, data *CategoryReference) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CategoryReference, error)
		FindOneBySubCategoryId(ctx context.Context, subCategoryId int64) (*CategoryReference, error)
		Update(ctx context.Context, data *CategoryReference) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCategoryReferenceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CategoryReference struct {
		Id            int64          `db:"id"`              // 主键
		SubCategoryId int64          `db:"sub_category_id"` // 子分类ID
		Type          string         `db:"type"`            // 权威参考文本类型，link/pdf
		Link          sql.NullString `db:"link"`            // 权威参考文本链接
		Pdf           sql.NullString `db:"pdf"`             // 权威参考文本PDF链接（OSS）
	}
)

func newCategoryReferenceModel(conn sqlx.SqlConn) *defaultCategoryReferenceModel {
	return &defaultCategoryReferenceModel{
		conn:  conn,
		table: "`category_reference`",
	}
}

func (m *defaultCategoryReferenceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCategoryReferenceModel) FindOne(ctx context.Context, id int64) (*CategoryReference, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", categoryReferenceRows, m.table)
	var resp CategoryReference
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryReferenceModel) FindOneBySubCategoryId(ctx context.Context, subCategoryId int64) (*CategoryReference, error) {
	var resp CategoryReference
	query := fmt.Sprintf("select %s from %s where `sub_category_id` = ? limit 1", categoryReferenceRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, subCategoryId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryReferenceModel) Insert(ctx context.Context, data *CategoryReference) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, categoryReferenceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SubCategoryId, data.Type, data.Link, data.Pdf)
	return ret, err
}

func (m *defaultCategoryReferenceModel) Update(ctx context.Context, newData *CategoryReference) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, categoryReferenceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.SubCategoryId, newData.Type, newData.Link, newData.Pdf, newData.Id)
	return err
}

func (m *defaultCategoryReferenceModel) tableName() string {
	return m.table
}
