// Server: gozero
// Consumers: fastapi

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: gozero/sql_tools.proto

package gozerov1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GozeroSqlTools_Tables_FullMethodName = "/gozero.v1.GozeroSqlTools/Tables"
	GozeroSqlTools_Query_FullMethodName  = "/gozero.v1.GozeroSqlTools/Query"
)

// GozeroSqlToolsClient is the client API for GozeroSqlTools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GozeroSqlToolsClient interface {
	Tables(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
	Query(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type gozeroSqlToolsClient struct {
	cc grpc.ClientConnInterface
}

func NewGozeroSqlToolsClient(cc grpc.ClientConnInterface) GozeroSqlToolsClient {
	return &gozeroSqlToolsClient{cc}
}

func (c *gozeroSqlToolsClient) Tables(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, GozeroSqlTools_Tables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gozeroSqlToolsClient) Query(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, GozeroSqlTools_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GozeroSqlToolsServer is the server API for GozeroSqlTools service.
// All implementations must embed UnimplementedGozeroSqlToolsServer
// for forward compatibility.
type GozeroSqlToolsServer interface {
	Tables(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	Query(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedGozeroSqlToolsServer()
}

// UnimplementedGozeroSqlToolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGozeroSqlToolsServer struct{}

func (UnimplementedGozeroSqlToolsServer) Tables(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tables not implemented")
}
func (UnimplementedGozeroSqlToolsServer) Query(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedGozeroSqlToolsServer) mustEmbedUnimplementedGozeroSqlToolsServer() {}
func (UnimplementedGozeroSqlToolsServer) testEmbeddedByValue()                        {}

// UnsafeGozeroSqlToolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GozeroSqlToolsServer will
// result in compilation errors.
type UnsafeGozeroSqlToolsServer interface {
	mustEmbedUnimplementedGozeroSqlToolsServer()
}

func RegisterGozeroSqlToolsServer(s grpc.ServiceRegistrar, srv GozeroSqlToolsServer) {
	// If the following call pancis, it indicates UnimplementedGozeroSqlToolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GozeroSqlTools_ServiceDesc, srv)
}

func _GozeroSqlTools_Tables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GozeroSqlToolsServer).Tables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GozeroSqlTools_Tables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GozeroSqlToolsServer).Tables(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GozeroSqlTools_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GozeroSqlToolsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GozeroSqlTools_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GozeroSqlToolsServer).Query(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GozeroSqlTools_ServiceDesc is the grpc.ServiceDesc for GozeroSqlTools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GozeroSqlTools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gozero.v1.GozeroSqlTools",
	HandlerType: (*GozeroSqlToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tables",
			Handler:    _GozeroSqlTools_Tables_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _GozeroSqlTools_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gozero/sql_tools.proto",
}
