// Server: gozero
// Consumers: spring

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: gozero/task.proto

package gozerov1

import (
	commonv1 "app/proto/commonv1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GozeroTask_Syncer_FullMethodName = "/gozero.v1.GozeroTask/Syncer"
)

// GozeroTaskClient is the client API for GozeroTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GozeroTaskClient interface {
	Syncer(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error)
}

type gozeroTaskClient struct {
	cc grpc.ClientConnInterface
}

func NewGozeroTaskClient(cc grpc.ClientConnInterface) GozeroTaskClient {
	return &gozeroTaskClient{cc}
}

func (c *gozeroTaskClient) Syncer(ctx context.Context, in *commonv1.JsonRequest, opts ...grpc.CallOption) (*commonv1.Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonv1.Result)
	err := c.cc.Invoke(ctx, GozeroTask_Syncer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GozeroTaskServer is the server API for GozeroTask service.
// All implementations must embed UnimplementedGozeroTaskServer
// for forward compatibility.
type GozeroTaskServer interface {
	Syncer(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error)
	mustEmbedUnimplementedGozeroTaskServer()
}

// UnimplementedGozeroTaskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGozeroTaskServer struct{}

func (UnimplementedGozeroTaskServer) Syncer(context.Context, *commonv1.JsonRequest) (*commonv1.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Syncer not implemented")
}
func (UnimplementedGozeroTaskServer) mustEmbedUnimplementedGozeroTaskServer() {}
func (UnimplementedGozeroTaskServer) testEmbeddedByValue()                    {}

// UnsafeGozeroTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GozeroTaskServer will
// result in compilation errors.
type UnsafeGozeroTaskServer interface {
	mustEmbedUnimplementedGozeroTaskServer()
}

func RegisterGozeroTaskServer(s grpc.ServiceRegistrar, srv GozeroTaskServer) {
	// If the following call pancis, it indicates UnimplementedGozeroTaskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GozeroTask_ServiceDesc, srv)
}

func _GozeroTask_Syncer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonv1.JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GozeroTaskServer).Syncer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GozeroTask_Syncer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GozeroTaskServer).Syncer(ctx, req.(*commonv1.JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GozeroTask_ServiceDesc is the grpc.ServiceDesc for GozeroTask service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GozeroTask_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gozero.v1.GozeroTask",
	HandlerType: (*GozeroTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Syncer",
			Handler:    _GozeroTask_Syncer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gozero/task.proto",
}
