// Server: gozero
// Consumers: spring

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gozero/task.proto

package gozerov1

import (
	commonv1 "app/proto/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gozero_task_proto protoreflect.FileDescriptor

const file_gozero_task_proto_rawDesc = "" +
	"\n" +
	"\x11gozero/task.proto\x12\tgozero.v1\x1a\x13common/result.proto2A\n" +
	"\n" +
	"GozeroTask\x123\n" +
	"\x06Syncer\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB-\n" +
	"\x17com.hcsy.gozeroproto.v1Z\x12app/proto/gozerov1b\x06proto3"

var file_gozero_task_proto_goTypes = []any{
	(*commonv1.JsonRequest)(nil), // 0: common.v1.JsonRequest
	(*commonv1.Result)(nil),      // 1: common.v1.Result
}
var file_gozero_task_proto_depIdxs = []int32{
	0, // 0: gozero.v1.GozeroTask.Syncer:input_type -> common.v1.JsonRequest
	1, // 1: gozero.v1.GozeroTask.Syncer:output_type -> common.v1.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gozero_task_proto_init() }
func file_gozero_task_proto_init() {
	if File_gozero_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gozero_task_proto_rawDesc), len(file_gozero_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gozero_task_proto_goTypes,
		DependencyIndexes: file_gozero_task_proto_depIdxs,
	}.Build()
	File_gozero_task_proto = out.File
	file_gozero_task_proto_goTypes = nil
	file_gozero_task_proto_depIdxs = nil
}
