// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spring/article.proto

package com.hcsy.spring.proto.article.v1;

public final class ArticleOuterClass {
  private ArticleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024spring/article.proto\022\tspring.v1\032\023commo" +
      "n/result.proto2\314\002\n\007Article\0221\n\004List\022\026.com" +
      "mon.v1.JsonRequest\032\021.common.v1.Result\0222\n" +
      "\005Batch\022\026.common.v1.JsonRequest\032\021.common." +
      "v1.Result\0220\n\003Get\022\026.common.v1.JsonRequest" +
      "\032\021.common.v1.Result\0224\n\007ByTitle\022\026.common." +
      "v1.JsonRequest\032\021.common.v1.Result\0227\n\nVie" +
      "wsBatch\022\026.common.v1.JsonRequest\032\021.common" +
      ".v1.Result\0229\n\014UserArticles\022\026.common.v1.J" +
      "sonRequest\032\021.common.v1.ResultB8\n com.hcs" +
      "y.spring.proto.article.v1P\001Z\022app/proto/s" +
      "pringv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
