// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gozero/task.proto

package com.hcsy.gozeroproto.v1;

public final class Task {
  private Task() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gozero/task.proto\022\tgozero.v1\032\023common/r" +
      "esult.proto2A\n\nGozeroTask\0223\n\006Syncer\022\026.co" +
      "mmon.v1.JsonRequest\032\021.common.v1.ResultB-" +
      "\n\027com.hcsy.gozeroproto.v1Z\022app/proto/goz" +
      "erov1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
