apisix:
  node_listen: 9080
  enable_ipv6: false
  proxy_mode: http
  enable_dev_mode: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
  admin:
    enable_admin: false

discovery:
  nacos:
    host:
      - "http://nacos:8848"
    prefix: "/nacos/v1/"
    fetch_interval: 5
    weight: 100
    timeout:
      connect: 2000
      send: 2000
      read: 5000

plugins:
  - mocking
  - cors
  - forward-auth
  - limit-req
  - proxy-rewrite
  - response-rewrite
  - opentelemetry

nginx_config:
  http:
    enable_access_log: true
    access_log_format: '{"time":"$time_iso8601","level":"INFO","trace_id":"$opentelemetry_trace_id","remote_addr":"$remote_addr","request":"$request","status":$status,"request_time":$request_time}'
    access_log_format_escape: json
  http_configuration_snippet: |
    proxy_buffering off;
  http_server_configuration_snippet: |
    location /swagger-ui/ {
        alias /usr/local/apisix/html/swagger-ui/;
        index index.html;
        try_files $uri $uri/ /swagger-ui/index.html;
    }
  error_log_level: warn

plugin_attr:
  opentelemetry:
    resource:
      service.name: apisix-gateway
    collector:
      address: otel-collector:4318
      request_timeout: 3
    enable_span_name_prefix: true
    set_ngx_var: true
