// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package aiHistory

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"app/model"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiHistoryFieldNames          = builder.RawFieldNames(&AiHistory{})
	aiHistoryRows                = strings.Join(aiHistoryFieldNames, ",")
	aiHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(aiHistoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiHistoryRowsWithPlaceHolder = strings.Join(stringx.Remove(aiHistoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	aiHistoryModel interface {
		Insert(ctx context.Context, data *AiHistory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiHistory, error)
		Update(ctx context.Context, data *AiHistory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiHistoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiHistory struct {
		Id        int64          `db:"id"`
		UserId    int64          `db:"user_id"`
		Ask       string         `db:"ask"`
		Reply     string         `db:"reply"`
		Thinking  sql.NullString `db:"thinking"`
		AiType    sql.NullString `db:"ai_type"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newAiHistoryModel(conn sqlx.SqlConn) *defaultAiHistoryModel {
	return &defaultAiHistoryModel{
		conn:  conn,
		table: "`ai_history`",
	}
}

func (m *defaultAiHistoryModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiHistoryModel) FindOne(ctx context.Context, id int64) (*AiHistory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiHistoryRows, m.table)
	var resp AiHistory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiHistoryModel) Insert(ctx context.Context, data *AiHistory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, aiHistoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Ask, data.Reply, data.Thinking, data.AiType)
	return ret, err
}

func (m *defaultAiHistoryModel) Update(ctx context.Context, data *AiHistory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aiHistoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Ask, data.Reply, data.Thinking, data.AiType, data.Id)
	return err
}

func (m *defaultAiHistoryModel) tableName() string {
	return m.table
}
