// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ArticleEsItem struct {
	Id                int64   `json:"id"`
	Title             string  `json:"title"`
	Content           string  `json:"content"`
	UserId            int64   `json:"userId"`
	Username          string  `json:"username"`
	Tags              string  `json:"tags"`
	Status            int     `json:"status"`
	Views             int     `json:"views"`
	LikeCount         int     `json:"likeCount"`
	CollectCount      int     `json:"collectCount"`
	AuthorFollowCount int     `json:"authorFollowCount"`
	CategoryName      string  `json:"category_name"`
	SubCategoryName   string  `json:"sub_category_name"`
	CreateAt          string  `json:"create_at"`
	UpdateAt          string  `json:"update_at"`
	AiScore           float64 `json:"ai_score"`
	UserScore         float64 `json:"user_score"`
	AiCommentCount    int     `json:"ai_comment_count"`
	UserCommentCount  int     `json:"user_comment_count"`
}

type ChatGetAllUnreadCountsReq struct {
	UserId string `json:"userId"`
}

type ChatGetAllUnreadCountsResp struct {
	Data map[string]int64 `json:"data"`
}

type ChatGetHistoryReq struct {
	UserId  string `json:"userId"`
	OtherId string `json:"otherId"`
	Page    int    `json:"page,optional"`
	Size    int    `json:"size,optional"`
}

type ChatGetHistoryResp struct {
	Messages []ChatMessageItem `json:"messages"`
	Total    int64             `json:"total"`
}

type ChatGetQueueStatusResp struct {
	OnlineUsers []string `json:"onlineUsers"`
	Count       int      `json:"count"`
}

type ChatGetUnreadCountReq struct {
	UserId  string `json:"userId"`
	OtherId string `json:"otherId"`
}

type ChatGetUnreadCountResp struct {
	UnreadCount int64 `json:"unreadCount"`
}

type ChatJoinQueueReq struct {
	UserId string `json:"userId"`
}

type ChatJoinQueueResp struct {
	UserId string `json:"userId"`
	Status string `json:"status"`
}

type ChatLeaveQueueReq struct {
	UserId string `json:"userId"`
}

type ChatLeaveQueueResp struct {
	UserId string `json:"userId"`
	Status string `json:"status"`
}

type ChatMessageItem struct {
	Id         uint64 `json:"id"`
	SenderId   string `json:"senderId"`
	ReceiverId string `json:"receiverId"`
	Content    string `json:"content"`
	IsRead     int8   `json:"isRead"`
	CreatedAt  string `json:"createdAt"`
}

type ChatSSEConnectReq struct {
	UserId *string `form:"userId,optional"`
}

type ChatSSEConnectResp struct {
}

type ChatSendMessageReq struct {
	SenderId   string `json:"senderId"`
	ReceiverId string `json:"receiverId"`
	Content    string `json:"content"`
}

type ChatSendMessageResp struct {
	MessageId uint64 `json:"messageId"`
}

type ChatWsConnectReq struct {
	UserId *string `form:"userId,optional"`
}

type ChatWsConnectResp struct {
}

type GetSearchHistoryReq struct {
	UserId string `path:"userId"`
}

type GetSearchHistoryResp struct {
	Keywords []string `json:"keywords"`
}

type SearchArticlesReq struct {
	Keyword         *string `form:"keyword,optional"`
	UserId          *uint64 `form:"userId,optional"`
	Username        *string `form:"username,optional"`
	CategoryName    *string `form:"category_name,optional"`
	SubCategoryName *string `form:"sub_category_name,optional"`
	StartDate       *string `form:"startDate,optional"`
	EndDate         *string `form:"endDate,optional"`
	Page            int     `form:"page,optional,default=1"`
	Size            int     `form:"size,optional,default=10"`
}

type SearchArticlesResp struct {
	Total int             `json:"total"`
	List  []ArticleEsItem `json:"list"`
}

type SyncESReq struct {
}

type SyncESResp struct {
}

type TestFastAPIResp struct {
	Data string `json:"data"`
}

type TestGoZeroResp struct {
	Data string `json:"data"`
}

type TestNestJSResp struct {
	Data string `json:"data"`
}

type TestSpringResp struct {
	Data string `json:"data"`
}
