// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ArticleEsItem struct {
	Id                int64                `json:"id"`
	Title             string               `json:"title"`
	Content           string               `json:"content"`
	UserId            int64                `json:"user_id"`
	Username          string               `json:"username"`
	Tags              string               `json:"tags"`
	Status            int                  `json:"status"`
	Views             int                  `json:"views"`
	LikeCount         int                  `json:"like_count"`
	CollectCount      int                  `json:"collect_count"`
	AuthorFollowCount int                  `json:"author_follow_count"`
	CategoryName      string               `json:"category_name"`
	SubCategoryName   string               `json:"sub_category_name"`
	CreateAt          string               `json:"create_at"`
	UpdateAt          string               `json:"update_at"`
	AiScore           float64              `json:"ai_score"`
	UserScore         float64              `json:"user_score"`
	AiCommentCount    int                  `json:"ai_comment_count"`
	UserCommentCount  int                  `json:"user_comment_count"`
	EsScore           float64              `json:"es_score"`
	VectorScore       float64              `json:"vector_score"`
	GraphScore        float64              `json:"graph_score"`
	FinalScore        float64              `json:"final_score"`
	Reason            string               `json:"reason"`
	SemanticReason    string               `json:"semantic_reason"`
	Relations         []GraphRelation      `json:"relations"`
	MatchedChunks     []VectorMatchedChunk `json:"matched_chunks"`
	ScoreDetails      ScoreDetails         `json:"score_details"`
}

type ChatGetAllUnreadCountsReq struct {
	UserId int64 `json:"user_id" validate:"gt=0"`
}

type ChatGetAllUnreadCountsResp struct {
	Data map[int64]int64 `json:"data"`
}

type ChatGetHistoryReq struct {
	UserId  int64 `json:"user_id" validate:"gt=0"`
	OtherId int64 `json:"other_id" validate:"gt=0"`
	Page    int   `json:"page,optional" validate:"gt=0"`
	Size    int   `json:"size,optional" validate:"gt=0"`
}

type ChatGetHistoryResp struct {
	Messages []ChatMessageItem `json:"messages"`
	Total    int64             `json:"total"`
}

type ChatGetQueueStatusResp struct {
	OnlineUsers []int64 `json:"online_users"`
	Count       int     `json:"count"`
}

type ChatGetUnreadCountReq struct {
	UserId  int64 `json:"user_id" validate:"gt=0"`
	OtherId int64 `json:"other_id" validate:"gt=0"`
}

type ChatGetUnreadCountResp struct {
	UnreadCount int64 `json:"unread_count"`
}

type ChatJoinQueueReq struct {
	UserId int64 `json:"user_id" validate:"gt=0"`
}

type ChatJoinQueueResp struct {
	UserId int64  `json:"user_id"`
	Status string `json:"status"`
}

type ChatLeaveQueueReq struct {
	UserId int64 `json:"user_id" validate:"gt=0"`
}

type ChatLeaveQueueResp struct {
	UserId int64  `json:"user_id"`
	Status string `json:"status"`
}

type ChatMessageItem struct {
	Id         uint64 `json:"id"`
	SenderId   int64  `json:"sender_id"`
	ReceiverId int64  `json:"receiver_id"`
	Content    string `json:"content"`
	IsRead     int8   `json:"is_read"`
	CreatedAt  string `json:"created_at"`
}

type ChatSSEConnectReq struct {
	UserId *int64 `form:"user_id,optional" validate:"omitempty,gt=0"`
}

type ChatSSEMessage struct {
	Type         string           `json:"type"`
	UserId       int64            `json:"user_id"`
	UnreadCounts map[int64]int64  `json:"unread_counts"`
	Message      *ChatMessageItem `json:"message,omitempty"`
}

type ChatSendMessageReq struct {
	SenderId   int64  `json:"sender_id" validate:"gt=0"`
	ReceiverId int64  `json:"receiver_id" validate:"gt=0"`
	Content    string `json:"content" validate:"notblank"`
}

type ChatSendMessageResp struct {
	MessageId uint64 `json:"message_id"`
}

type ChatWsConnectReq struct {
	UserId *int64 `form:"user_id,optional" validate:"omitempty,gt=0"`
}

type ChatWsMessage struct {
	Type       string `json:"type"`
	SenderId   int64  `json:"sender_id,omitempty"`
	ReceiverId int64  `json:"receiver_id,omitempty"`
	Content    string `json:"content,omitempty"`
	MessageId  uint64 `json:"message_id,omitempty"`
	Timestamp  string `json:"timestamp,omitempty"`
}

type GetSearchHistoryReq struct {
	UserId string `path:"user_id" validate:"notblank,positiveint"`
}

type GetSearchHistoryResp struct {
	Keywords []string `json:"keywords"`
}

type GraphRelation struct {
	Type   string  `json:"type"`
	Name   string  `json:"name"`
	Score  float64 `json:"score"`
	Reason string  `json:"reason"`
}

type ScoreDetails struct {
	EsScore       float64 `json:"es_score"`
	VectorScore   float64 `json:"vector_score"`
	GraphScore    float64 `json:"graph_score"`
	BusinessScore float64 `json:"business_score"`
	RecencyScore  float64 `json:"recency_score"`
}

type SearchArticlesReq struct {
	Keyword         *string `form:"keyword,optional"`
	UserId          *uint64 `form:"user_id,optional" validate:"omitempty,gt=0"`
	Username        *string `form:"username,optional"`
	CategoryName    *string `form:"category_name,optional"`
	SubCategoryName *string `form:"sub_category_name,optional"`
	StartDate       *string `form:"start_date,optional" validate:"omitempty,notblank,datetime"`
	EndDate         *string `form:"end_date,optional" validate:"omitempty,notblank,datetime,notbefore=StartDate"`
	Page            int     `form:"page,optional,default=1" validate:"gt=0"`
	Size            int     `form:"size,optional,default=10" validate:"gt=0"`
	Mode            *string `form:"mode,optional" validate:"omitempty,searchmode"`
	EnableVector    *bool   `form:"enable_vector,optional"`
	EnableGraph     *bool   `form:"enable_graph,optional"`
	Explain         *bool   `form:"explain,optional"`
}

type SearchArticlesResp struct {
	Total int             `json:"total"`
	List  []ArticleEsItem `json:"list"`
}

type SqlToolsColumnInfo struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Key     string `json:"key"`
	Comment string `json:"comment"`
}

type SqlToolsGetTablesReq struct {
	Table string `json:"table,optional" validate:"maxrunes=64"`
}

type SqlToolsGetTablesResp struct {
	Data []SqlToolsTableInfo `json:"data"`
}

type SqlToolsQueryReq struct {
	Query  string            `json:"query" validate:"notblank,maxrunes=8000"`
	Params map[string]string `json:"params,optional"`
}

type SqlToolsQueryResp struct {
	Data SqlToolsQueryResult `json:"data"`
}

type SqlToolsQueryResult struct {
	Columns  []string   `json:"columns"`
	Rows     [][]string `json:"rows"`
	RowCount int        `json:"rowCount"`
}

type SqlToolsTableInfo struct {
	Table   string               `json:"table"`
	Columns []SqlToolsColumnInfo `json:"columns,optional"`
}

type SyncESReq struct {
}

type SyncESResp struct {
}

type TestGoZeroResp struct {
	Data string `json:"data"`
}

type VectorMatchedChunk struct {
	ArticleId  int64   `json:"article_id"`
	Title      string  `json:"title"`
	ChunkIndex int     `json:"chunk_index"`
	Score      float64 `json:"score"`
	Content    string  `json:"content"`
}
