// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ArticleEsItem struct {
	Id                int64                `json:"id"`
	Title             string               `json:"title"`
	Content           string               `json:"content"`
	UserId            int64                `json:"user_id"`
	Username          string               `json:"username"`
	Tags              string               `json:"tags"`
	Status            int                  `json:"status"`
	Views             int                  `json:"views"`
	LikeCount         int                  `json:"like_count"`
	CollectCount      int                  `json:"collect_count"`
	AuthorFollowCount int                  `json:"author_follow_count"`
	CategoryName      string               `json:"category_name"`
	SubCategoryName   string               `json:"sub_category_name"`
	CreateAt          string               `json:"create_at"`
	UpdateAt          string               `json:"update_at"`
	AiScore           float64              `json:"ai_score"`
	UserScore         float64              `json:"user_score"`
	AiCommentCount    int                  `json:"ai_comment_count"`
	UserCommentCount  int                  `json:"user_comment_count"`
	EsScore           float64              `json:"es_score"`
	VectorScore       float64              `json:"vector_score"`
	GraphScore        float64              `json:"graph_score"`
	FinalScore        float64              `json:"final_score"`
	Reason            string               `json:"reason"`
	SemanticReason    string               `json:"semantic_reason"`
	Relations         []GraphRelation      `json:"relations"`
	MatchedChunks     []VectorMatchedChunk `json:"matched_chunks"`
	ScoreDetails      ScoreDetails         `json:"score_details"`
}

type ChatGetAllUnreadCountsReq struct {
	UserId string `json:"user_id"`
}

type ChatGetAllUnreadCountsResp struct {
	Data map[string]int64 `json:"data"`
}

type ChatGetHistoryReq struct {
	UserId  string `json:"user_id"`
	OtherId string `json:"other_id"`
	Page    int    `json:"page,optional"`
	Size    int    `json:"size,optional"`
}

type ChatGetHistoryResp struct {
	Messages []ChatMessageItem `json:"messages"`
	Total    int64             `json:"total"`
}

type ChatGetQueueStatusResp struct {
	OnlineUsers []string `json:"online_users"`
	Count       int      `json:"count"`
}

type ChatGetUnreadCountReq struct {
	UserId  string `json:"user_id"`
	OtherId string `json:"other_id"`
}

type ChatGetUnreadCountResp struct {
	UnreadCount int64 `json:"unread_count"`
}

type ChatJoinQueueReq struct {
	UserId string `json:"user_id"`
}

type ChatJoinQueueResp struct {
	UserId string `json:"user_id"`
	Status string `json:"status"`
}

type ChatLeaveQueueReq struct {
	UserId string `json:"user_id"`
}

type ChatLeaveQueueResp struct {
	UserId string `json:"user_id"`
	Status string `json:"status"`
}

type ChatMessageItem struct {
	Id         uint64 `json:"id"`
	SenderId   string `json:"sender_id"`
	ReceiverId string `json:"receiver_id"`
	Content    string `json:"content"`
	IsRead     int8   `json:"is_read"`
	CreatedAt  string `json:"created_at"`
}

type ChatSSEConnectReq struct {
	UserId *string `form:"user_id,optional"`
}

type ChatSSEConnectResp struct {
}

type ChatSendMessageReq struct {
	SenderId   string `json:"sender_id"`
	ReceiverId string `json:"receiver_id"`
	Content    string `json:"content"`
}

type ChatSendMessageResp struct {
	MessageId uint64 `json:"message_id"`
}

type ChatWsConnectReq struct {
	UserId *string `form:"user_id,optional"`
}

type ChatWsConnectResp struct {
}

type GetSearchHistoryReq struct {
	UserId string `path:"user_id"`
}

type GetSearchHistoryResp struct {
	Keywords []string `json:"keywords"`
}

type GraphRelation struct {
	Type   string  `json:"type"`
	Name   string  `json:"name"`
	Score  float64 `json:"score"`
	Reason string  `json:"reason"`
}

type ScoreDetails struct {
	EsScore       float64 `json:"es_score"`
	VectorScore   float64 `json:"vector_score"`
	GraphScore    float64 `json:"graph_score"`
	BusinessScore float64 `json:"business_score"`
	RecencyScore  float64 `json:"recency_score"`
}

type SearchArticlesReq struct {
	Keyword         *string `form:"keyword,optional"`
	UserId          *uint64 `form:"user_id,optional"`
	Username        *string `form:"username,optional"`
	CategoryName    *string `form:"category_name,optional"`
	SubCategoryName *string `form:"sub_category_name,optional"`
	StartDate       *string `form:"start_date,optional"`
	EndDate         *string `form:"end_date,optional"`
	Page            int     `form:"page,optional,default=1"`
	Size            int     `form:"size,optional,default=10"`
	Mode            *string `form:"mode,optional"`
	EnableVector    *bool   `form:"enable_vector,optional"`
	EnableGraph     *bool   `form:"enable_graph,optional"`
	Explain         *bool   `form:"explain,optional"`
}

type SearchArticlesResp struct {
	Total int             `json:"total"`
	List  []ArticleEsItem `json:"list"`
}

type SyncESReq struct {
}

type SyncESResp struct {
}

type TestFastAPIResp struct {
	Data string `json:"data"`
}

type TestGoZeroResp struct {
	Data string `json:"data"`
}

type TestNestJSResp struct {
	Data string `json:"data"`
}

type TestSpringResp struct {
	Data string `json:"data"`
}

type VectorMatchedChunk struct {
	ArticleId  int64   `json:"article_id"`
	Title      string  `json:"title"`
	ChunkIndex int     `json:"chunk_index"`
	Score      float64 `json:"score"`
	Content    string  `json:"content"`
}
