// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/result.proto

package com.hcsy.spring.proto.common.v1;

public interface JsonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.v1.JsonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes payload = 1;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
