// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/result.proto

package com.hcsy.spring.proto.common.v1;

public final class ResultOuterClass {
  private ResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_v1_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_v1_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_v1_JsonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_v1_JsonRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023common/result.proto\022\tcommon.v1\"5\n\006Resu" +
      "lt\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\014\n\004dat" +
      "a\030\003 \001(\014\"\036\n\013JsonRequest\022\017\n\007payload\030\001 \001(\014B" +
      "7\n\037com.hcsy.spring.proto.common.v1P\001Z\022ap" +
      "p/proto/commonv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_v1_Result_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_v1_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_v1_Result_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
    internal_static_common_v1_JsonRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_v1_JsonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_v1_JsonRequest_descriptor,
        new java.lang.String[] { "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
