# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.common import result_pb2 as common_dot_result__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nestjs/log_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchHistory = channel.unary_unary(
                '/nestjs.v1.Log/SearchHistory',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.ViewDistribution = channel.unary_unary(
                '/nestjs.v1.Log/ViewDistribution',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.SearchKeywords = channel.unary_unary(
                '/nestjs.v1.Log/SearchKeywords',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.ApiAverageSpeed = channel.unary_unary(
                '/nestjs.v1.Log/ApiAverageSpeed',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.ApiCalledCount = channel.unary_unary(
                '/nestjs.v1.Log/ApiCalledCount',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)


class LogServicer:
    """Missing associated documentation comment in .proto file."""

    def SearchHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewDistribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKeywords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApiAverageSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApiCalledCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchHistory,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'ViewDistribution': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewDistribution,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'SearchKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKeywords,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'ApiAverageSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.ApiAverageSpeed,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'ApiCalledCount': grpc.unary_unary_rpc_method_handler(
                    servicer.ApiCalledCount,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nestjs.v1.Log', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nestjs.v1.Log', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Log:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nestjs.v1.Log/SearchHistory',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewDistribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nestjs.v1.Log/ViewDistribution',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nestjs.v1.Log/SearchKeywords',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApiAverageSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nestjs.v1.Log/ApiAverageSpeed',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApiCalledCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nestjs.v1.Log/ApiCalledCount',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
