# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nestjs/log.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'nestjs/log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nestjs/log.proto\x12\tnestjs.v1\x1a\x13\x63ommon/result.proto2\xb8\x02\n\x03Log\x12:\n\rSearchHistory\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12=\n\x10ViewDistribution\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12;\n\x0eSearchKeywords\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12<\n\x0f\x41piAverageSpeed\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12;\n\x0e\x41piCalledCount\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB2\n\x1c\x63om.hcsy.nestjs.proto.log.v1Z\x12\x61pp/proto/nestjsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nestjs.log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.hcsy.nestjs.proto.log.v1Z\022app/proto/nestjsv1'
  _globals['_LOG']._serialized_start=53
  _globals['_LOG']._serialized_end=365
# @@protoc_insertion_point(module_scope)
