// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package likes

import (
	"app/model"
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likesFieldNames          = builder.RawFieldNames(&Likes{})
	likesRows                = strings.Join(likesFieldNames, ",")
	likesRowsExpectAutoSet   = strings.Join(stringx.Remove(likesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	likesRowsWithPlaceHolder = strings.Join(stringx.Remove(likesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	likesModel interface {
		Insert(ctx context.Context, data *Likes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Likes, error)
		FindOneByArticleIdUserId(ctx context.Context, articleId int64, userId int64) (*Likes, error)
		Update(ctx context.Context, data *Likes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLikesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Likes struct {
		Id          int64     `db:"id"`           // 主键
		ArticleId   int64     `db:"article_id"`   // 文章ID
		UserId      int64     `db:"user_id"`      // 用户ID
		CreatedTime time.Time `db:"created_time"` // 创建时间
	}
)

func newLikesModel(conn sqlx.SqlConn) *defaultLikesModel {
	return &defaultLikesModel{
		conn:  conn,
		table: "`likes`",
	}
}

func (m *defaultLikesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLikesModel) FindOne(ctx context.Context, id int64) (*Likes, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likesRows, m.table)
	var resp Likes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) FindOneByArticleIdUserId(ctx context.Context, articleId int64, userId int64) (*Likes, error) {
	var resp Likes
	query := fmt.Sprintf("select %s from %s where `article_id` = ? and `user_id` = ? limit 1", likesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, articleId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) Insert(ctx context.Context, data *Likes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, likesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.UserId, data.CreatedTime)
	return ret, err
}

func (m *defaultLikesModel) Update(ctx context.Context, newData *Likes) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, likesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ArticleId, newData.UserId, newData.CreatedTime, newData.Id)
	return err
}

func (m *defaultLikesModel) tableName() string {
	return m.table
}
