// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package chatMessages

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"app/model"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatMessagesFieldNames          = builder.RawFieldNames(&ChatMessages{})
	chatMessagesRows                = strings.Join(chatMessagesFieldNames, ",")
	chatMessagesRowsExpectAutoSet   = strings.Join(stringx.Remove(chatMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatMessagesRowsWithPlaceHolder = strings.Join(stringx.Remove(chatMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	chatMessagesModel interface {
		Insert(ctx context.Context, data *ChatMessages) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ChatMessages, error)
		Update(ctx context.Context, data *ChatMessages) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultChatMessagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChatMessages struct {
		Id         uint64    `db:"id"`          // 消息ID，主键
		SenderId   string    `db:"sender_id"`   // 发送者ID
		ReceiverId string    `db:"receiver_id"` // 接收者ID
		Content    string    `db:"content"`     // 消息内容
		IsRead     int64     `db:"is_read"`     // 是否已读，0未读，1已读
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
	}
)

func newChatMessagesModel(conn sqlx.SqlConn) *defaultChatMessagesModel {
	return &defaultChatMessagesModel{
		conn:  conn,
		table: "`chat_messages`",
	}
}

func (m *defaultChatMessagesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChatMessagesModel) FindOne(ctx context.Context, id uint64) (*ChatMessages, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatMessagesRows, m.table)
	var resp ChatMessages
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatMessagesModel) Insert(ctx context.Context, data *ChatMessages) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, chatMessagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.Content, data.IsRead)
	return ret, err
}

func (m *defaultChatMessagesModel) Update(ctx context.Context, data *ChatMessages) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatMessagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.Content, data.IsRead, data.Id)
	return err
}

func (m *defaultChatMessagesModel) tableName() string {
	return m.table
}
