# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fastapi/ai_history.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fastapi/ai_history.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66\x61stapi/ai_history.proto\x12\nfastapi.v1\x1a\x13\x63ommon/result.proto2\xa7\x01\n\tAiHistory\x12\x30\n\x03Get\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x33\n\x06Update\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x33\n\x06\x44\x65lete\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB\x15Z\x13\x61pp/proto/fastapiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastapi.ai_history_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023app/proto/fastapiv1'
  _globals['_AIHISTORY']._serialized_start=62
  _globals['_AIHISTORY']._serialized_end=229
# @@protoc_insertion_point(module_scope)
