# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fastapi/algorithm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fastapi/algorithm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66\x61stapi/algorithm.proto\x12\nfastapi.v1\x1a\x13\x63ommon/result.proto\"\x0e\n\x0c\x45mptyRequest2\xd2\x01\n\tAlgorithm\x12?\n\x10GetSearchWeights\x12\x18.fastapi.v1.EmptyRequest\x1a\x11.common.v1.Result\x12>\n\x0fGetSearchScript\x12\x18.fastapi.v1.EmptyRequest\x1a\x11.common.v1.Result\x12\x44\n\x15GetSearchScriptParams\x12\x18.fastapi.v1.EmptyRequest\x1a\x11.common.v1.ResultB9\n com.hcsy.spring.proto.fastapi.v1P\x01Z\x13\x61pp/proto/fastapiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastapi.algorithm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.hcsy.spring.proto.fastapi.v1P\001Z\023app/proto/fastapiv1'
  _globals['_EMPTYREQUEST']._serialized_start=60
  _globals['_EMPTYREQUEST']._serialized_end=74
  _globals['_ALGORITHM']._serialized_start=77
  _globals['_ALGORITHM']._serialized_end=287
# @@protoc_insertion_point(module_scope)
