# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.common import result_pb2 as common_dot_result__pb2
from app.proto.fastapi import algorithm_pb2 as fastapi_dot_algorithm__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fastapi/algorithm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlgorithmStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSearchWeights = channel.unary_unary(
                '/fastapi.v1.Algorithm/GetSearchWeights',
                request_serializer=fastapi_dot_algorithm__pb2.EmptyRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.GetSearchScript = channel.unary_unary(
                '/fastapi.v1.Algorithm/GetSearchScript',
                request_serializer=fastapi_dot_algorithm__pb2.EmptyRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.GetSearchScriptParams = channel.unary_unary(
                '/fastapi.v1.Algorithm/GetSearchScriptParams',
                request_serializer=fastapi_dot_algorithm__pb2.EmptyRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)


class AlgorithmServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSearchWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearchScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearchScriptParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSearchWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchWeights,
                    request_deserializer=fastapi_dot_algorithm__pb2.EmptyRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetSearchScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchScript,
                    request_deserializer=fastapi_dot_algorithm__pb2.EmptyRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetSearchScriptParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchScriptParams,
                    request_deserializer=fastapi_dot_algorithm__pb2.EmptyRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fastapi.v1.Algorithm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fastapi.v1.Algorithm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Algorithm:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSearchWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastapi.v1.Algorithm/GetSearchWeights',
            fastapi_dot_algorithm__pb2.EmptyRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSearchScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastapi.v1.Algorithm/GetSearchScript',
            fastapi_dot_algorithm__pb2.EmptyRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSearchScriptParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastapi.v1.Algorithm/GetSearchScriptParams',
            fastapi_dot_algorithm__pb2.EmptyRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
