# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fastapi/search_enhance.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fastapi/search_enhance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66\x61stapi/search_enhance.proto\x12\nfastapi.v1\x1a\x13\x63ommon/result.proto\"\xa9\x01\n\x13GraphEnhanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x13\n\x0b\x61rticle_ids\x18\x03 \x03(\x03\x12\x15\n\rcategory_name\x18\x04 \x01(\t\x12\x19\n\x11sub_category_name\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12\r\n\x05limit\x18\x07 \x01(\x05\x12\x0c\n\x04mode\x18\x08 \x01(\t\"\xb9\x01\n\x14VectorEnhanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x13\n\x0b\x61rticle_ids\x18\x03 \x03(\x03\x12\x15\n\rcategory_name\x18\x04 \x01(\t\x12\x19\n\x11sub_category_name\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12\r\n\x05limit\x18\x07 \x01(\x05\x12\r\n\x05top_k\x18\x08 \x01(\x05\x12\x0c\n\x04mode\x18\t \x01(\t2\x99\x01\n\rSearchEnhance\x12\x42\n\x0c\x45nhanceGraph\x12\x1f.fastapi.v1.GraphEnhanceRequest\x1a\x11.common.v1.Result\x12\x44\n\rEnhanceVector\x12 .fastapi.v1.VectorEnhanceRequest\x1a\x11.common.v1.ResultB9\n com.hcsy.spring.proto.fastapi.v1P\x01Z\x13\x61pp/proto/fastapiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastapi.search_enhance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.hcsy.spring.proto.fastapi.v1P\001Z\023app/proto/fastapiv1'
  _globals['_GRAPHENHANCEREQUEST']._serialized_start=66
  _globals['_GRAPHENHANCEREQUEST']._serialized_end=235
  _globals['_VECTORENHANCEREQUEST']._serialized_start=238
  _globals['_VECTORENHANCEREQUEST']._serialized_end=423
  _globals['_SEARCHENHANCE']._serialized_start=426
  _globals['_SEARCHENHANCE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
