# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fastapi/task.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fastapi/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66\x61stapi/task.proto\x12\nfastapi.v1\x1a\x13\x63ommon/result.proto2\xbf\x01\n\x0b\x46\x61stapiTask\x12\x37\n\nSyncVector\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12?\n\x12\x43learAnalyzeCaches\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x36\n\tSyncNeo4j\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB0\n\x19\x63om.hcsy.fastapi.proto.v1Z\x13\x61pp/proto/fastapiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastapi.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.hcsy.fastapi.proto.v1Z\023app/proto/fastapiv1'
  _globals['_FASTAPITASK']._serialized_start=56
  _globals['_FASTAPITASK']._serialized_end=247
# @@protoc_insertion_point(module_scope)
