// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fastapi/task.proto

package com.hcsy.fastapi.proto.v1;

public final class Task {
  private Task() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022fastapi/task.proto\022\nfastapi.v1\032\023common" +
      "/result.proto2\277\001\n\013FastapiTask\0227\n\nSyncVec" +
      "tor\022\026.common.v1.JsonRequest\032\021.common.v1." +
      "Result\022?\n\022ClearAnalyzeCaches\022\026.common.v1" +
      ".JsonRequest\032\021.common.v1.Result\0226\n\tSyncN" +
      "eo4j\022\026.common.v1.JsonRequest\032\021.common.v1" +
      ".ResultB0\n\031com.hcsy.fastapi.proto.v1Z\023ap" +
      "p/proto/fastapiv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
