// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package focus

import (
	"app/model"
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	focusFieldNames          = builder.RawFieldNames(&Focus{})
	focusRows                = strings.Join(focusFieldNames, ",")
	focusRowsExpectAutoSet   = strings.Join(stringx.Remove(focusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	focusRowsWithPlaceHolder = strings.Join(stringx.Remove(focusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	focusModel interface {
		Insert(ctx context.Context, data *Focus) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Focus, error)
		FindOneByUserIdFocusId(ctx context.Context, userId int64, focusId int64) (*Focus, error)
		Update(ctx context.Context, data *Focus) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFocusModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Focus struct {
		Id          int64     `db:"id"`           // 主键
		UserId      int64     `db:"user_id"`      // 用户ID
		FocusId     int64     `db:"focus_id"`     // 关注的用户ID
		CreatedTime time.Time `db:"created_time"` // 创建时间
	}
)

func newFocusModel(conn sqlx.SqlConn) *defaultFocusModel {
	return &defaultFocusModel{
		conn:  conn,
		table: "`focus`",
	}
}

func (m *defaultFocusModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFocusModel) FindOne(ctx context.Context, id int64) (*Focus, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", focusRows, m.table)
	var resp Focus
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFocusModel) FindOneByUserIdFocusId(ctx context.Context, userId int64, focusId int64) (*Focus, error) {
	var resp Focus
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `focus_id` = ? limit 1", focusRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, focusId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFocusModel) Insert(ctx context.Context, data *Focus) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, focusRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FocusId, data.CreatedTime)
	return ret, err
}

func (m *defaultFocusModel) Update(ctx context.Context, newData *Focus) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, focusRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.FocusId, newData.CreatedTime, newData.Id)
	return err
}

func (m *defaultFocusModel) tableName() string {
	return m.table
}
