// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nestjs/email.proto

package com.hcsy.nestjs.proto.email.v1;

public final class EmailOuterClass {
  private EmailOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022nestjs/email.proto\022\tnestjs.v1\032\023common/" +
      "result.proto2>\n\005Email\0225\n\010SendCode\022\026.comm" +
      "on.v1.JsonRequest\032\021.common.v1.ResultB4\n\036" +
      "com.hcsy.nestjs.proto.email.v1Z\022app/prot" +
      "o/nestjsv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
