// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v3.21.12
// source: nestjs/email.proto

/* eslint-disable */
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { JsonRequest, Result } from "../common/result";

export const protobufPackage = "nestjs.v1";

/**
 * Server: nestjs
 * Consumers: spring
 */

export const NESTJS_V1_PACKAGE_NAME = "nestjs.v1";

export interface EmailClient {
  sendCode(request: JsonRequest): Observable<Result>;
}

export interface EmailController {
  sendCode(request: JsonRequest): Promise<Result> | Observable<Result> | Result;
}

export function EmailControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendCode"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Email", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Email", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EMAIL_SERVICE_NAME = "Email";

export type EmailService = typeof EmailService;
export const EmailService = {
  sendCode: {
    path: "/nestjs.v1.Email/SendCode" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
} as const;

export interface EmailServer extends UntypedServiceImplementation {
  sendCode: handleUnaryCall<JsonRequest, Result>;
}
