// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v3.21.12
// source: nestjs/log.proto

/* eslint-disable */
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { JsonRequest, Result } from "../common/result";

export const protobufPackage = "nestjs.v1";

/**
 * Server: nestjs
 * Consumers: gozero,fastapi
 */

export const NESTJS_V1_PACKAGE_NAME = "nestjs.v1";

export interface LogClient {
  searchHistory(request: JsonRequest): Observable<Result>;

  viewDistribution(request: JsonRequest): Observable<Result>;

  searchKeywords(request: JsonRequest): Observable<Result>;

  apiAverageSpeed(request: JsonRequest): Observable<Result>;

  apiCalledCount(request: JsonRequest): Observable<Result>;
}

export interface LogController {
  searchHistory(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  viewDistribution(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  searchKeywords(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  apiAverageSpeed(request: JsonRequest): Promise<Result> | Observable<Result> | Result;

  apiCalledCount(request: JsonRequest): Promise<Result> | Observable<Result> | Result;
}

export function LogControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "searchHistory",
      "viewDistribution",
      "searchKeywords",
      "apiAverageSpeed",
      "apiCalledCount",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Log", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Log", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LOG_SERVICE_NAME = "Log";

export type LogService = typeof LogService;
export const LogService = {
  searchHistory: {
    path: "/nestjs.v1.Log/SearchHistory" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  viewDistribution: {
    path: "/nestjs.v1.Log/ViewDistribution" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  searchKeywords: {
    path: "/nestjs.v1.Log/SearchKeywords" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  apiAverageSpeed: {
    path: "/nestjs.v1.Log/ApiAverageSpeed" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
  apiCalledCount: {
    path: "/nestjs.v1.Log/ApiCalledCount" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JsonRequest): Buffer => Buffer.from(JsonRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JsonRequest => JsonRequest.decode(value),
    responseSerialize: (value: Result): Buffer => Buffer.from(Result.encode(value).finish()),
    responseDeserialize: (value: Buffer): Result => Result.decode(value),
  },
} as const;

export interface LogServer extends UntypedServiceImplementation {
  searchHistory: handleUnaryCall<JsonRequest, Result>;
  viewDistribution: handleUnaryCall<JsonRequest, Result>;
  searchKeywords: handleUnaryCall<JsonRequest, Result>;
  apiAverageSpeed: handleUnaryCall<JsonRequest, Result>;
  apiCalledCount: handleUnaryCall<JsonRequest, Result>;
}
