# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spring/article.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'spring/article.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14spring/article.proto\x12\tspring.v1\x1a\x13\x63ommon/result.proto2\xcc\x02\n\x07\x41rticle\x12\x31\n\x04List\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x32\n\x05\x42\x61tch\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x30\n\x03Get\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x34\n\x07\x42yTitle\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x37\n\nViewsBatch\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x39\n\x0cUserArticles\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB8\n com.hcsy.spring.proto.article.v1P\x01Z\x12\x61pp/proto/springv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spring.article_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.hcsy.spring.proto.article.v1P\001Z\022app/proto/springv1'
  _globals['_ARTICLE']._serialized_start=57
  _globals['_ARTICLE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
