# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.common import result_pb2 as common_dot_result__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spring/article_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArticleStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/spring.v1.Article/List',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.Batch = channel.unary_unary(
                '/spring.v1.Article/Batch',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/spring.v1.Article/Get',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.ByTitle = channel.unary_unary(
                '/spring.v1.Article/ByTitle',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.ViewsBatch = channel.unary_unary(
                '/spring.v1.Article/ViewsBatch',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.UserArticles = channel.unary_unary(
                '/spring.v1.Article/UserArticles',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)


class ArticleServicer:
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Batch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ByTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArticleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'ByTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.ByTitle,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'ViewsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewsBatch,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'UserArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.UserArticles,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spring.v1.Article', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spring.v1.Article', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Article:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Article/List',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Article/Batch',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Article/Get',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Article/ByTitle',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Article/ViewsBatch',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Article/UserArticles',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
