# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spring/category.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'spring/category.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15spring/category.proto\x12\tspring.v1\x1a\x13\x63ommon/result.proto2\x9e\x02\n\x08\x43\x61tegory\x12\x32\n\x05\x42\x61tch\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x35\n\x08SubBatch\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x30\n\x03\x41ll\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12:\n\rSubWithParent\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x39\n\x0cReferenceSub\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB7\n!com.hcsy.spring.proto.category.v1Z\x12\x61pp/proto/springv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spring.category_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.hcsy.spring.proto.category.v1Z\022app/proto/springv1'
  _globals['_CATEGORY']._serialized_start=58
  _globals['_CATEGORY']._serialized_end=344
# @@protoc_insertion_point(module_scope)
