# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.common import result_pb2 as common_dot_result__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spring/statistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatisticsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Article = channel.unary_unary(
                '/spring.v1.Statistics/Article',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.Interaction = channel.unary_unary(
                '/spring.v1.Statistics/Interaction',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.Follow = channel.unary_unary(
                '/spring.v1.Statistics/Follow',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.UserPortrait = channel.unary_unary(
                '/spring.v1.Statistics/UserPortrait',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)


class StatisticsServicer:
    """Missing associated documentation comment in .proto file."""

    def Article(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Follow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserPortrait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Article': grpc.unary_unary_rpc_method_handler(
                    servicer.Article,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'Interaction': grpc.unary_unary_rpc_method_handler(
                    servicer.Interaction,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'Follow': grpc.unary_unary_rpc_method_handler(
                    servicer.Follow,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'UserPortrait': grpc.unary_unary_rpc_method_handler(
                    servicer.UserPortrait,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spring.v1.Statistics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spring.v1.Statistics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Statistics:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Article(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Statistics/Article',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Statistics/Interaction',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Follow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Statistics/Follow',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserPortrait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.Statistics/UserPortrait',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
