# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spring/statistics.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'spring/statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import result_pb2 as common_dot_result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17spring/statistics.proto\x12\tspring.v1\x1a\x13\x63ommon/result.proto2\xec\x01\n\nStatistics\x12\x34\n\x07\x41rticle\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x38\n\x0bInteraction\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x33\n\x06\x46ollow\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.Result\x12\x39\n\x0cUserPortrait\x12\x16.common.v1.JsonRequest\x1a\x11.common.v1.ResultB9\n#com.hcsy.spring.proto.statistics.v1Z\x12\x61pp/proto/springv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spring.statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.hcsy.spring.proto.statistics.v1Z\022app/proto/springv1'
  _globals['_STATISTICS']._serialized_start=60
  _globals['_STATISTICS']._serialized_end=296
# @@protoc_insertion_point(module_scope)
