# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.common import result_pb2 as common_dot_result__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spring/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/spring.v1.User/Get',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.Batch = channel.unary_unary(
                '/spring.v1.User/Batch',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.ByName = channel.unary_unary(
                '/spring.v1.User/ByName',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.ByGithubId = channel.unary_unary(
                '/spring.v1.User/ByGithubId',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.GithubUser = channel.unary_unary(
                '/spring.v1.User/GithubUser',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.IsAdmin = channel.unary_unary(
                '/spring.v1.User/IsAdmin',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)
        self.TokenTicket = channel.unary_unary(
                '/spring.v1.User/TokenTicket',
                request_serializer=common_dot_result__pb2.JsonRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.Result.FromString,
                _registered_method=True)


class UserServicer:
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Batch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ByGithubId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GithubUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TokenTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'ByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ByName,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'ByGithubId': grpc.unary_unary_rpc_method_handler(
                    servicer.ByGithubId,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'GithubUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GithubUser,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'IsAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAdmin,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
            'TokenTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenTicket,
                    request_deserializer=common_dot_result__pb2.JsonRequest.FromString,
                    response_serializer=common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spring.v1.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spring.v1.User', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class User:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.User/Get',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.User/Batch',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.User/ByName',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ByGithubId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.User/ByGithubId',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GithubUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.User/GithubUser',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.User/IsAdmin',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TokenTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spring.v1.User/TokenTicket',
            common_dot_result__pb2.JsonRequest.SerializeToString,
            common_dot_result__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
