// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package articles

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"app/model"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articlesFieldNames          = builder.RawFieldNames(&Articles{})
	articlesRows                = strings.Join(articlesFieldNames, ",")
	articlesRowsExpectAutoSet   = strings.Join(stringx.Remove(articlesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articlesRowsWithPlaceHolder = strings.Join(stringx.Remove(articlesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articlesModel interface {
		Insert(ctx context.Context, data *Articles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Articles, error)
		Update(ctx context.Context, data *Articles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticlesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Articles struct {
		Id            int64     `db:"id"`              // 文章id
		Title         string    `db:"title"`           // 文章标题
		Content       string    `db:"content"`         // 文章内容
		UserId        int64     `db:"user_id"`         // 用户id
		SubCategoryId int64     `db:"sub_category_id"` // 子分类id
		Tags          string    `db:"tags"`            // 文章标签
		Status        int64     `db:"status"`          // 文章状态
		Views         int64     `db:"views"`           // 文章浏览量
		CreateAt      time.Time `db:"create_at"`       // 创建时间
		UpdateAt      time.Time `db:"update_at"`       // 更新时间
	}
)

func newArticlesModel(conn sqlx.SqlConn) *defaultArticlesModel {
	return &defaultArticlesModel{
		conn:  conn,
		table: "`articles`",
	}
}

func (m *defaultArticlesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticlesModel) FindOne(ctx context.Context, id int64) (*Articles, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articlesRows, m.table)
	var resp Articles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticlesModel) Insert(ctx context.Context, data *Articles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, articlesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId, data.SubCategoryId, data.Tags, data.Status, data.Views)
	return ret, err
}

func (m *defaultArticlesModel) Update(ctx context.Context, data *Articles) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articlesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId, data.SubCategoryId, data.Tags, data.Status, data.Views, data.Id)
	return err
}

func (m *defaultArticlesModel) tableName() string {
	return m.table
}
