// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package collects

import (
	"app/model"
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectsFieldNames          = builder.RawFieldNames(&Collects{})
	collectsRows                = strings.Join(collectsFieldNames, ",")
	collectsRowsExpectAutoSet   = strings.Join(stringx.Remove(collectsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	collectsRowsWithPlaceHolder = strings.Join(stringx.Remove(collectsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	collectsModel interface {
		Insert(ctx context.Context, data *Collects) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Collects, error)
		FindOneByArticleIdUserId(ctx context.Context, articleId int64, userId int64) (*Collects, error)
		Update(ctx context.Context, data *Collects) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCollectsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Collects struct {
		Id          int64     `db:"id"`           // 主键
		ArticleId   int64     `db:"article_id"`   // 文章ID
		UserId      int64     `db:"user_id"`      // 用户ID
		CreatedTime time.Time `db:"created_time"` // 创建时间
	}
)

func newCollectsModel(conn sqlx.SqlConn) *defaultCollectsModel {
	return &defaultCollectsModel{
		conn:  conn,
		table: "`collects`",
	}
}

func (m *defaultCollectsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCollectsModel) FindOne(ctx context.Context, id int64) (*Collects, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectsRows, m.table)
	var resp Collects
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectsModel) FindOneByArticleIdUserId(ctx context.Context, articleId int64, userId int64) (*Collects, error) {
	var resp Collects
	query := fmt.Sprintf("select %s from %s where `article_id` = ? and `user_id` = ? limit 1", collectsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, articleId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectsModel) Insert(ctx context.Context, data *Collects) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, collectsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.UserId, data.CreatedTime)
	return ret, err
}

func (m *defaultCollectsModel) Update(ctx context.Context, newData *Collects) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ArticleId, newData.UserId, newData.CreatedTime, newData.Id)
	return err
}

func (m *defaultCollectsModel) tableName() string {
	return m.table
}
