// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package subCategory

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"app/model"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subCategoryFieldNames          = builder.RawFieldNames(&SubCategory{})
	subCategoryRows                = strings.Join(subCategoryFieldNames, ",")
	subCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(subCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	subCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(subCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	subCategoryModel interface {
		Insert(ctx context.Context, data *SubCategory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SubCategory, error)
		Update(ctx context.Context, data *SubCategory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSubCategoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SubCategory struct {
		Id         int64     `db:"id"`          // 主键
		Name       string    `db:"name"`        // 子分类名称
		CategoryId int64     `db:"category_id"` // 所属分类ID
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newSubCategoryModel(conn sqlx.SqlConn) *defaultSubCategoryModel {
	return &defaultSubCategoryModel{
		conn:  conn,
		table: "`sub_category`",
	}
}

func (m *defaultSubCategoryModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSubCategoryModel) FindOne(ctx context.Context, id int64) (*SubCategory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subCategoryRows, m.table)
	var resp SubCategory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubCategoryModel) Insert(ctx context.Context, data *SubCategory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, subCategoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.CategoryId)
	return ret, err
}

func (m *defaultSubCategoryModel) Update(ctx context.Context, data *SubCategory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, subCategoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.CategoryId, data.Id)
	return err
}

func (m *defaultSubCategoryModel) tableName() string {
	return m.table
}
