// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spring/statistics.proto

package com.hcsy.spring.proto.statistics.v1;

public final class StatisticsOuterClass {
  private StatisticsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027spring/statistics.proto\022\tspring.v1\032\023co" +
      "mmon/result.proto2\354\001\n\nStatistics\0224\n\007Arti" +
      "cle\022\026.common.v1.JsonRequest\032\021.common.v1." +
      "Result\0228\n\013Interaction\022\026.common.v1.JsonRe" +
      "quest\032\021.common.v1.Result\0223\n\006Follow\022\026.com" +
      "mon.v1.JsonRequest\032\021.common.v1.Result\0229\n" +
      "\014UserPortrait\022\026.common.v1.JsonRequest\032\021." +
      "common.v1.ResultB9\n#com.hcsy.spring.prot" +
      "o.statistics.v1Z\022app/proto/springv1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor(),
        });
    com.hcsy.spring.proto.common.v1.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
